#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""批次產生 A1 003–012（簡單過去式）與新等級 B1 001–005（present perfect/條件句/意見）。
   對話、<file>.json（含 reorder/dictation）、scenes、manifest。沿用 gen_lessons.py 的角色/場景。
   從 english_learning/ 執行：  python tools/gen_a1_b1.py
"""
import json
import gen_lessons as G

SKY = G.SKY
WARM = ("#fed7aa", "#fff7ed")
PINK = ("#fce7f3", "#fdf2f8")
PURPLE = ("#ede9fe", "#f5f3ff")
WOOD = ("#d6a87c", "#b8855c")
SAND = ("#fde68a", "#fcd34d")
NIGHT = ("#1e293b", "#334155")

A1 = [
  {"id":"003","title":"003 · The Lost Cat","scene":"lost-cat","aria":"Anna tells Tom how she found her lost cat",
   "grad":SKY,"decor":G.SUN+G.cloud(64),"L":"Anna","R":"Tom","lbub":"Lost!","rbub":"Found!",
   "props":[("🐈",168,116,30,True),("🌳",320,118,32),("🏠",44,142,26)],
   "dialogue":[("Anna","I lost my cat yesterday."),("Tom","Oh no! What happened?"),("Anna","She ran out of the house."),
     ("Tom","Did you look for her?"),("Anna","Yes, I looked everywhere."),("Tom","Where did you find her?"),
     ("Anna","I found her under a tree."),("Tom","Was she okay?"),("Anna","Yes, she was hungry but happy."),
     ("Tom","I am glad you found her!")],
   "content":{
     "quiz3":[{"q":"Anna lost her cat.","answer":"Yes"},{"q":"The cat ran out of the house.","answer":"Yes"},
       {"q":"Anna looked everywhere.","answer":"Yes"},{"q":"Anna found the cat under a tree.","answer":"Yes"},
       {"q":"The cat was okay.","answer":"Yes"}],
     "quiz4":[{"q":"Tom lost his cat.","answer":"No"},{"q":"The cat ran into the house.","answer":"No"},
       {"q":"Anna found the cat on the roof.","answer":"No"},{"q":"The cat was hungry.","answer":"Yes"},
       {"q":"Anna found her cat.","answer":"Yes"}],
     "vocab":[{"word":"Anna","pic":"👧"},{"word":"Tom","pic":"👦"},{"word":"cat","pic":"🐈"},
       {"word":"house","pic":"🏠"},{"word":"tree","pic":"🌳"},{"word":"look","pic":"👀"}],
     "wh":[{"q":"What did Anna lose?","a":"She lost her cat.","wrong":["She lost her dog.","She lost her bag."]},
       {"q":"What did the cat do?","a":"It ran out of the house.","wrong":["It slept all day.","It ate the food."]},
       {"q":"Where did Anna find the cat?","a":"Under a tree.","wrong":["On the bed.","In the car."]},
       {"q":"How was the cat?","a":"It was hungry but happy.","wrong":["It was sick.","It was angry."]},
       {"q":"When did Anna lose the cat?","a":"Yesterday.","wrong":["Today.","Last year."]}],
     "clozeType":"category",
     "cloze":[{"text":"I lost my ___ yesterday.","answer":"cat","wrong":["dog","bird"]},
       {"text":"She ran out of the ___.","answer":"house","wrong":["school","shop"]},
       {"text":"I looked ___.","answer":"everywhere","wrong":["here","there"]},
       {"text":"I found her under a ___.","answer":"tree","wrong":["bush","flower"]}],
     "reorder":[["I","lost","my","cat","yesterday"],["She","ran","out","of","the","house"],
       ["I","looked","everywhere"],["I","found","her","under","a","tree"]],
     "dictation":["I lost my cat yesterday.","She ran out of the house.","I looked everywhere.","I found her under a tree."]}},

  {"id":"004","title":"004 · My Birthday Party","scene":"bday-party","aria":"Ben tells Lily about his birthday party",
   "grad":PINK,"decor":G.SUN+G.cloud(70),"L":"Ben","R":"Lily","lbub":"Party!","rbub":"Cake!",
   "props":[("🎂",168,116,30,True),("🎁",44,146,24),("🎈",322,58,24)],
   "dialogue":[("Ben","I had my birthday party yesterday."),("Lily","Happy birthday! Was it fun?"),
     ("Ben","Yes, it was great. Many friends came."),("Lily","What did you do?"),
     ("Ben","We played games and ate pizza."),("Lily","Did you have a cake?"),("Ben","Yes, a big chocolate cake."),
     ("Lily","What did you get?"),("Ben","I got a new bike and some books."),("Lily","Wow! You are lucky.")],
   "content":{
     "quiz3":[{"q":"Ben had a birthday party.","answer":"Yes"},{"q":"Many friends came.","answer":"Yes"},
       {"q":"They played games and ate pizza.","answer":"Yes"},{"q":"Ben had a chocolate cake.","answer":"Yes"},
       {"q":"Ben got a new bike.","answer":"Yes"}],
     "quiz4":[{"q":"Lily had a birthday party.","answer":"No"},{"q":"They ate soup.","answer":"No"},
       {"q":"The cake was vanilla.","answer":"No"},{"q":"Ben got a new bike.","answer":"Yes"},
       {"q":"The party was fun.","answer":"Yes"}],
     "vocab":[{"word":"Ben","pic":"👦"},{"word":"Lily","pic":"👧"},{"word":"cake","pic":"🎂"},
       {"word":"pizza","pic":"🍕"},{"word":"bike","pic":"🚲"},{"word":"books","pic":"📚"}],
     "wh":[{"q":"Whose birthday was it?","a":"It was Ben's birthday.","wrong":["It was Lily's birthday.","It was Tom's birthday."]},
       {"q":"What did they eat?","a":"They ate pizza.","wrong":["They ate rice.","They ate soup."]},
       {"q":"What kind of cake?","a":"A chocolate cake.","wrong":["A vanilla cake.","A cheese cake."]},
       {"q":"What did Ben get?","a":"A new bike and books.","wrong":["A new phone.","A dog."]},
       {"q":"When was the party?","a":"Yesterday.","wrong":["Tomorrow.","Last year."]}],
     "clozeType":"category",
     "cloze":[{"text":"We played games and ate ___.","answer":"pizza","wrong":["pasta","bread"]},
       {"text":"I had a big chocolate ___.","answer":"cake","wrong":["pie","cookie"]},
       {"text":"I got a new ___.","answer":"bike","wrong":["car","scooter"]},
       {"text":"Many ___ came.","answer":"friends","wrong":["teachers","neighbors"]}],
     "reorder":[["I","had","my","birthday","party","yesterday"],["We","played","games","and","ate","pizza"],
       ["I","had","a","big","chocolate","cake"],["I","got","a","new","bike"]],
     "dictation":["I had my birthday party yesterday.","We played games and ate pizza.",
       "I had a big chocolate cake.","I got a new bike and some books."]}},

  {"id":"005","title":"005 · A Day at the Farm","scene":"farm","aria":"Tom tells Anna about a day at the farm",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Tom","R":"Anna","lbub":"Farm!","rbub":"Cow!",
   "props":[("🐄",168,116,30,True),("🐔",44,148,22),("🚜",318,140,30)],
   "dialogue":[("Tom","I went to a farm last weekend."),("Anna","That sounds fun! What did you see?"),
     ("Tom","I saw cows, pigs, and chickens."),("Anna","Did you feed the animals?"),("Tom","Yes, I fed the chickens."),
     ("Anna","What did the cows do?"),("Tom","They ate grass all day."),("Anna","Did you ride a horse?"),
     ("Tom","Yes, I rode a brown horse."),("Anna","I want to visit a farm, too!")],
   "content":{
     "quiz3":[{"q":"Tom went to a farm.","answer":"Yes"},{"q":"Tom saw cows, pigs, and chickens.","answer":"Yes"},
       {"q":"Tom fed the chickens.","answer":"Yes"},{"q":"The cows ate grass.","answer":"Yes"},
       {"q":"Tom rode a horse.","answer":"Yes"}],
     "quiz4":[{"q":"Anna went to a farm.","answer":"No"},{"q":"Tom saw lions and tigers.","answer":"No"},
       {"q":"Tom fed the cows.","answer":"No"},{"q":"Tom rode a brown horse.","answer":"Yes"},
       {"q":"Tom saw farm animals.","answer":"Yes"}],
     "vocab":[{"word":"Tom","pic":"👦"},{"word":"Anna","pic":"👧"},{"word":"cow","pic":"🐄"},
       {"word":"pig","pic":"🐷"},{"word":"chicken","pic":"🐔"},{"word":"horse","pic":"🐴"}],
     "wh":[{"q":"Where did Tom go?","a":"He went to a farm.","wrong":["He went to a zoo.","He went to school."]},
       {"q":"What did Tom see?","a":"Cows, pigs, and chickens.","wrong":["Lions and bears.","Fish and birds."]},
       {"q":"What did Tom feed?","a":"He fed the chickens.","wrong":["He fed the lions.","He fed the cats."]},
       {"q":"What did the cows do?","a":"They ate grass.","wrong":["They slept.","They ran away."]},
       {"q":"What did Tom ride?","a":"A brown horse.","wrong":["A white horse.","A bike."]}],
     "clozeType":"category",
     "cloze":[{"text":"I saw cows, pigs, and ___.","answer":"chickens","wrong":["ducks","sheep"]},
       {"text":"I fed the ___.","answer":"chickens","wrong":["goats","rabbits"]},
       {"text":"They ate ___ all day.","answer":"grass","wrong":["hay","corn"]},
       {"text":"I rode a brown ___.","answer":"horse","wrong":["pony","donkey"]}],
     "reorder":[["I","went","to","a","farm"],["I","saw","cows","and","pigs"],
       ["I","fed","the","chickens"],["I","rode","a","brown","horse"]],
     "dictation":["I went to a farm last weekend.","I saw cows, pigs, and chickens.",
       "I fed the chickens.","I rode a brown horse."]}},

  {"id":"006","title":"006 · The Snowman","scene":"snowman","aria":"Lily and Sam build a snowman",
   "grad":("#bae6fd","#eff6ff"),"ground":("#f1f5f9","#e2e8f0"),"decor":G.cloud(70)+G.cloud(240,"cloud2"),
   "L":"Lily","R":"Sam","lbub":"Snow!","rbub":"Snowman!",
   "props":[("⛄",168,116,30,True),("❄️",60,76,22),("🥕",320,146,20)],
   "dialogue":[("Lily","It snowed last night!"),("Sam","Yes! Let's make a snowman."),
     ("Lily","I made a big snowball for the body."),("Sam","I made a small one for the head."),
     ("Lily","We used a carrot for the nose."),("Sam","And two rocks for the eyes."),
     ("Lily","Our snowman looks great!"),("Sam","It was so cold outside."),
     ("Lily","But it was a lot of fun."),("Sam","Let's drink some hot cocoa now.")],
   "content":{
     "quiz3":[{"q":"It snowed last night.","answer":"Yes"},{"q":"They made a snowman.","answer":"Yes"},
       {"q":"They used a carrot for the nose.","answer":"Yes"},{"q":"They used rocks for the eyes.","answer":"Yes"},
       {"q":"It was cold outside.","answer":"Yes"}],
     "quiz4":[{"q":"It rained last night.","answer":"No"},{"q":"They made a sandcastle.","answer":"No"},
       {"q":"They used a banana for the nose.","answer":"No"},{"q":"It was cold outside.","answer":"Yes"},
       {"q":"They had fun.","answer":"Yes"}],
     "vocab":[{"word":"Lily","pic":"👧"},{"word":"Sam","pic":"👦"},{"word":"snow","pic":"❄️"},
       {"word":"snowman","pic":"⛄"},{"word":"carrot","pic":"🥕"},{"word":"cocoa","pic":"☕"}],
     "wh":[{"q":"What did they make?","a":"A snowman.","wrong":["A sandcastle.","A cake."]},
       {"q":"What did they use for the nose?","a":"A carrot.","wrong":["A banana.","A stick."]},
       {"q":"What did they use for the eyes?","a":"Two rocks.","wrong":["Two buttons.","Two coins."]},
       {"q":"How was the weather?","a":"It was cold.","wrong":["It was hot.","It was rainy."]},
       {"q":"What will they drink?","a":"Hot cocoa.","wrong":["Cold juice.","Water."]}],
     "clozeType":"category",
     "cloze":[{"text":"Let's make a ___.","answer":"snowman","wrong":["sandcastle","campfire"]},
       {"text":"We used a ___ for the nose.","answer":"carrot","wrong":["potato","onion"]},
       {"text":"And two ___ for the eyes.","answer":"rocks","wrong":["buttons","coins"]},
       {"text":"Let's drink some hot ___.","answer":"cocoa","wrong":["tea","milk"]}],
     "reorder":[["It","snowed","last","night"],["Let","us","make","a","snowman"],
       ["We","used","a","carrot","for","the","nose"],["It","was","so","cold","outside"]],
     "dictation":["It snowed last night.","Let us make a snowman.",
       "We used a carrot for the nose.","It was so cold outside."]}},

  {"id":"007","title":"007 · Shopping with Mom","scene":"shopping","aria":"Mia tells Ben about shopping with her mom",
   "grad":PURPLE,"decor":G.SUN+G.cloud(70),"L":"Mia","R":"Ben","lbub":"Shop!","rbub":"New!",
   "props":[("🛒",168,116,28,True),("🛍️",44,146,24),("🏬",318,118,32)],
   "dialogue":[("Mia","I went shopping with my mom."),("Ben","What did you buy?"),("Mia","We bought some new shoes."),
     ("Ben","Did you buy anything else?"),("Mia","Yes, we bought fruit and bread."),("Ben","Where did you go?"),
     ("Mia","We went to the big supermarket."),("Ben","Was it crowded?"),("Mia","Yes, there were many people."),
     ("Ben","Shopping can be tiring!")],
   "content":{
     "quiz3":[{"q":"Mia went shopping with her mom.","answer":"Yes"},{"q":"They bought new shoes.","answer":"Yes"},
       {"q":"They bought fruit and bread.","answer":"Yes"},{"q":"They went to the supermarket.","answer":"Yes"},
       {"q":"There were many people.","answer":"Yes"}],
     "quiz4":[{"q":"Mia went shopping with her dad.","answer":"No"},{"q":"They bought a new TV.","answer":"No"},
       {"q":"The shop was empty.","answer":"No"},{"q":"They bought new shoes.","answer":"Yes"},
       {"q":"They went to the supermarket.","answer":"Yes"}],
     "vocab":[{"word":"Mia","pic":"👧"},{"word":"Ben","pic":"👦"},{"word":"shoes","pic":"👟"},
       {"word":"fruit","pic":"🍎"},{"word":"bread","pic":"🍞"},{"word":"supermarket","pic":"🏬"}],
     "wh":[{"q":"Who did Mia go with?","a":"Her mom.","wrong":["Her dad.","Her friend."]},
       {"q":"What did they buy first?","a":"New shoes.","wrong":["A new bag.","A toy."]},
       {"q":"What food did they buy?","a":"Fruit and bread.","wrong":["Candy and soda.","Meat and rice."]},
       {"q":"Where did they go?","a":"The supermarket.","wrong":["The library.","The park."]},
       {"q":"How was the supermarket?","a":"Crowded.","wrong":["Empty.","Closed."]}],
     "clozeType":"category",
     "cloze":[{"text":"We bought some new ___.","answer":"shoes","wrong":["socks","hats"]},
       {"text":"We bought fruit and ___.","answer":"bread","wrong":["rice","milk"]},
       {"text":"We went to the big ___.","answer":"supermarket","wrong":["library","museum"]},
       {"text":"There were many ___.","answer":"people","wrong":["children","workers"]}],
     "reorder":[["I","went","shopping","with","my","mom"],["We","bought","some","new","shoes"],
       ["We","went","to","the","supermarket"],["There","were","many","people"]],
     "dictation":["I went shopping with my mom.","We bought some new shoes.",
       "We went to the big supermarket.","There were many people."]}},

  {"id":"008","title":"008 · The Soccer Game","scene":"soccer-game","aria":"Sam tells Leo about the soccer game",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Sam","R":"Leo","lbub":"Goal!","rbub":"Won!",
   "props":[("⚽",168,116,28,True),("🥅",44,140,28),("🏆",322,142,24)],
   "dialogue":[("Sam","We played a soccer game yesterday."),("Leo","Did your team win?"),("Sam","Yes, we won three to two!"),
     ("Leo","That's great! Who scored?"),("Sam","I scored two goals."),("Leo","Wow, you played really well."),
     ("Sam","My friend scored the last goal."),("Leo","Was the game hard?"),
     ("Sam","Yes, the other team was strong."),("Leo","Congratulations on the win!")],
   "content":{
     "quiz3":[{"q":"They played a soccer game.","answer":"Yes"},{"q":"Sam's team won.","answer":"Yes"},
       {"q":"The score was three to two.","answer":"Yes"},{"q":"Sam scored two goals.","answer":"Yes"},
       {"q":"The other team was strong.","answer":"Yes"}],
     "quiz4":[{"q":"They played a basketball game.","answer":"No"},{"q":"Sam's team lost.","answer":"No"},
       {"q":"Sam scored five goals.","answer":"No"},{"q":"Sam scored two goals.","answer":"Yes"},
       {"q":"Sam's friend scored the last goal.","answer":"Yes"}],
     "vocab":[{"word":"Sam","pic":"👦"},{"word":"Leo","pic":"👦"},{"word":"soccer","pic":"⚽"},
       {"word":"goal","pic":"🥅"},{"word":"trophy","pic":"🏆"},{"word":"team","pic":"👥"}],
     "wh":[{"q":"What game did they play?","a":"Soccer.","wrong":["Basketball.","Tennis."]},
       {"q":"Did Sam's team win?","a":"Yes, they won.","wrong":["No, they lost.","It was a tie."]},
       {"q":"What was the score?","a":"Three to two.","wrong":["Five to one.","Two to two."]},
       {"q":"How many goals did Sam score?","a":"Two goals.","wrong":["Three goals.","No goals."]},
       {"q":"How was the other team?","a":"Strong.","wrong":["Weak.","Lazy."]}],
     "clozeType":"category",
     "cloze":[{"text":"We played a ___ game.","answer":"soccer","wrong":["tennis","baseball"]},
       {"text":"We ___ three to two.","answer":"won","wrong":["lost","tied"]},
       {"text":"I scored two ___.","answer":"goals","wrong":["points","runs"]},
       {"text":"The other ___ was strong.","answer":"team","wrong":["player","coach"]}],
     "reorder":[["We","played","a","soccer","game"],["We","won","three","to","two"],
       ["I","scored","two","goals"],["The","other","team","was","strong"]],
     "dictation":["We played a soccer game yesterday.","We won three to two.",
       "I scored two goals.","The other team was strong."]}},

  {"id":"009","title":"009 · At the Library","scene":"library","aria":"Emma tells Tom about the library",
   "grad":("#fef3c7","#fffbeb"),"ground":WOOD,"decor":G.SUN+G.cloud(70),"L":"Emma","R":"Tom","lbub":"Books!","rbub":"Quiet!",
   "props":[("📚",168,116,28),("📖",44,146,24),("🤫",320,120,26)],
   "dialogue":[("Emma","I went to the library after school."),("Tom","What did you do there?"),
     ("Emma","I read a book about space."),("Tom","Did you borrow any books?"),("Emma","Yes, I borrowed three books."),
     ("Tom","Was the library quiet?"),("Emma","Yes, everyone was very quiet."),("Tom","What was your favorite book?"),
     ("Emma","The one about planets and stars."),("Tom","I love space books, too!")],
   "content":{
     "quiz3":[{"q":"Emma went to the library.","answer":"Yes"},{"q":"Emma read a book about space.","answer":"Yes"},
       {"q":"Emma borrowed three books.","answer":"Yes"},{"q":"The library was quiet.","answer":"Yes"},
       {"q":"Emma's favorite book was about planets.","answer":"Yes"}],
     "quiz4":[{"q":"Emma went to the library before school.","answer":"No"},{"q":"Emma read a book about animals.","answer":"No"},
       {"q":"Emma borrowed ten books.","answer":"No"},{"q":"The library was quiet.","answer":"Yes"},
       {"q":"Emma borrowed three books.","answer":"Yes"}],
     "vocab":[{"word":"Emma","pic":"👧"},{"word":"Tom","pic":"👦"},{"word":"library","pic":"📚"},
       {"word":"book","pic":"📖"},{"word":"space","pic":"🪐"},{"word":"star","pic":"⭐"}],
     "wh":[{"q":"Where did Emma go?","a":"To the library.","wrong":["To the park.","To the shop."]},
       {"q":"What did she read about?","a":"Space.","wrong":["Animals.","Sports."]},
       {"q":"How many books did she borrow?","a":"Three.","wrong":["One.","Ten."]},
       {"q":"How was the library?","a":"Quiet.","wrong":["Noisy.","Crowded."]},
       {"q":"What was her favorite book about?","a":"Planets and stars.","wrong":["Cars.","Cooking."]}],
     "clozeType":"category",
     "cloze":[{"text":"I went to the ___.","answer":"library","wrong":["museum","theater"]},
       {"text":"I read a ___ about space.","answer":"book","wrong":["magazine","comic"]},
       {"text":"I borrowed three ___.","answer":"books","wrong":["movies","games"]},
       {"text":"Everyone was very ___.","answer":"quiet","wrong":["calm","still"]}],
     "reorder":[["I","went","to","the","library"],["I","read","a","book","about","space"],
       ["I","borrowed","three","books"],["Everyone","was","very","quiet"]],
     "dictation":["I went to the library after school.","I read a book about space.",
       "I borrowed three books.","Everyone was very quiet."]}},

  {"id":"010","title":"010 · Baking a Cake","scene":"baking","aria":"Anna tells Lily how she baked a cake",
   "grad":("#fef3c7","#fffbeb"),"ground":WOOD,"decor":G.SUN+G.cloud(70),"L":"Anna","R":"Lily","lbub":"Bake!","rbub":"Yum!",
   "props":[("🍰",168,116,28,True),("🥣",44,146,24),("🥚",322,144,20)],
   "dialogue":[("Anna","Yesterday I baked a cake with my sister."),("Lily","That sounds fun! What kind of cake?"),
     ("Anna","We made a strawberry cake."),("Lily","How did you make it?"),("Anna","We mixed flour, eggs, and sugar."),
     ("Lily","Then what did you do?"),("Anna","We put it in the oven for an hour."),("Lily","Did it taste good?"),
     ("Anna","Yes, it was sweet and soft."),("Lily","I want a piece, please!")],
   "content":{
     "quiz3":[{"q":"Anna baked a cake.","answer":"Yes"},{"q":"They made a strawberry cake.","answer":"Yes"},
       {"q":"They mixed flour, eggs, and sugar.","answer":"Yes"},{"q":"They put it in the oven.","answer":"Yes"},
       {"q":"The cake was sweet.","answer":"Yes"}],
     "quiz4":[{"q":"Anna baked bread.","answer":"No"},{"q":"They made a chocolate cake.","answer":"No"},
       {"q":"They cooked it on the stove.","answer":"No"},{"q":"The cake was sweet and soft.","answer":"Yes"},
       {"q":"Anna baked with her sister.","answer":"Yes"}],
     "vocab":[{"word":"Anna","pic":"👧"},{"word":"Lily","pic":"👧"},{"word":"cake","pic":"🍰"},
       {"word":"egg","pic":"🥚"},{"word":"sugar","pic":"🍬"},{"word":"oven","pic":"🔥"}],
     "wh":[{"q":"What did Anna bake?","a":"A cake.","wrong":["Cookies.","Bread."]},
       {"q":"What kind of cake?","a":"Strawberry.","wrong":["Chocolate.","Lemon."]},
       {"q":"What did they mix?","a":"Flour, eggs, and sugar.","wrong":["Rice and beans.","Milk and salt."]},
       {"q":"Where did they put the cake?","a":"In the oven.","wrong":["In the fridge.","On the table."]},
       {"q":"How did the cake taste?","a":"Sweet and soft.","wrong":["Sour.","Salty."]}],
     "clozeType":"category",
     "cloze":[{"text":"We made a strawberry ___.","answer":"cake","wrong":["pie","muffin"]},
       {"text":"We mixed flour, eggs, and ___.","answer":"sugar","wrong":["salt","butter"]},
       {"text":"We put it in the ___.","answer":"oven","wrong":["fridge","microwave"]},
       {"text":"It was sweet and ___.","answer":"soft","wrong":["warm","fresh"]}],
     "reorder":[["I","baked","a","cake","with","my","sister"],["We","mixed","flour","eggs","and","sugar"],
       ["We","put","it","in","the","oven"],["It","was","sweet","and","soft"]],
     "dictation":["Yesterday I baked a cake with my sister.","We mixed flour, eggs, and sugar.",
       "We put it in the oven for an hour.","It was sweet and soft."]}},

  {"id":"011","title":"011 · Camping Night","scene":"camping","aria":"Leo tells Mia about a camping night",
   "grad":NIGHT,"ground":("#1e293b","#0f172a"),
   "decor":G.moon("#1e293b")+G.stars([(60,40,1.8),(110,30,1.4),(250,46,1.6),(300,54,1.8),(40,66,1.3)]),
   "L":"Leo","R":"Mia","lbub":"Camp!","rbub":"Stars!",
   "props":[("⛺",168,118,30),("🔥",44,146,24),("⭐",320,46,20,True)],
   "dialogue":[("Leo","Last summer we went camping."),("Mia","Where did you sleep?"),("Leo","We slept in a big tent."),
     ("Mia","Was it scary at night?"),("Leo","A little, but we made a campfire."),("Mia","What did you do at the campfire?"),
     ("Leo","We cooked food and sang songs."),("Mia","Did you see the stars?"),
     ("Leo","Yes, the sky was full of stars."),("Mia","Camping sounds amazing!")],
   "content":{
     "quiz3":[{"q":"They went camping last summer.","answer":"Yes"},{"q":"They slept in a tent.","answer":"Yes"},
       {"q":"They made a campfire.","answer":"Yes"},{"q":"They cooked food and sang songs.","answer":"Yes"},
       {"q":"The sky was full of stars.","answer":"Yes"}],
     "quiz4":[{"q":"They went camping last winter.","answer":"No"},{"q":"They slept in a hotel.","answer":"No"},
       {"q":"They watched TV at night.","answer":"No"},{"q":"They made a campfire.","answer":"Yes"},
       {"q":"They saw many stars.","answer":"Yes"}],
     "vocab":[{"word":"Leo","pic":"👦"},{"word":"Mia","pic":"👧"},{"word":"tent","pic":"⛺"},
       {"word":"campfire","pic":"🔥"},{"word":"star","pic":"⭐"},{"word":"song","pic":"🎵"}],
     "wh":[{"q":"When did they go camping?","a":"Last summer.","wrong":["Last winter.","Yesterday."]},
       {"q":"Where did they sleep?","a":"In a tent.","wrong":["In a house.","In a car."]},
       {"q":"What did they make?","a":"A campfire.","wrong":["A snowman.","A sandcastle."]},
       {"q":"What did they do at the campfire?","a":"Cooked food and sang songs.","wrong":["Watched TV.","Did homework."]},
       {"q":"What did they see in the sky?","a":"Many stars.","wrong":["The sun.","Airplanes."]}],
     "clozeType":"category",
     "cloze":[{"text":"We slept in a big ___.","answer":"tent","wrong":["cabin","hut"]},
       {"text":"We made a ___.","answer":"campfire","wrong":["picnic","sandcastle"]},
       {"text":"We cooked food and sang ___.","answer":"songs","wrong":["poems","stories"]},
       {"text":"The sky was full of ___.","answer":"stars","wrong":["clouds","birds"]}],
     "reorder":[["Last","summer","we","went","camping"],["We","slept","in","a","big","tent"],
       ["We","cooked","food","and","sang","songs"],["The","sky","was","full","of","stars"]],
     "dictation":["Last summer we went camping.","We slept in a big tent.",
       "We cooked food and sang songs.","The sky was full of stars."]}},

  {"id":"012","title":"012 · The Sandcastle","scene":"sandcastle","aria":"Ben tells Emma about the beach",
   "grad":("#7dd3fc","#e0f2fe"),"ground":SAND,"decor":G.SUN+G.cloud(70),"L":"Ben","R":"Emma","lbub":"Beach!","rbub":"Castle!",
   "props":[("🏰",168,116,28,True),("🪣",44,148,22),("🌊",320,146,24)],
   "dialogue":[("Ben","We went to the beach on Sunday."),("Emma","Did you swim in the sea?"),
     ("Ben","Yes, and we built a big sandcastle."),("Emma","How big was it?"),
     ("Ben","It was taller than my little brother!"),("Emma","Did you find any shells?"),
     ("Ben","Yes, we collected many shells."),("Emma","Did the waves break your castle?"),
     ("Ben","Yes, but we laughed and built another one."),("Emma","The beach is the best place in summer!")],
   "content":{
     "quiz3":[{"q":"They went to the beach on Sunday.","answer":"Yes"},{"q":"They built a sandcastle.","answer":"Yes"},
       {"q":"The castle was tall.","answer":"Yes"},{"q":"They collected many shells.","answer":"Yes"},
       {"q":"The waves broke the castle.","answer":"Yes"}],
     "quiz4":[{"q":"They went to the beach on Monday.","answer":"No"},{"q":"They built a snowman.","answer":"No"},
       {"q":"They found no shells.","answer":"No"},{"q":"They built a sandcastle.","answer":"Yes"},
       {"q":"They built another castle.","answer":"Yes"}],
     "vocab":[{"word":"Ben","pic":"👦"},{"word":"Emma","pic":"👧"},{"word":"beach","pic":"🏖️"},
       {"word":"sandcastle","pic":"🏰"},{"word":"shell","pic":"🐚"},{"word":"wave","pic":"🌊"}],
     "wh":[{"q":"When did they go to the beach?","a":"On Sunday.","wrong":["On Monday.","In winter."]},
       {"q":"What did they build?","a":"A sandcastle.","wrong":["A snowman.","A treehouse."]},
       {"q":"How big was the castle?","a":"Taller than his brother.","wrong":["Very small.","As big as a house."]},
       {"q":"What did they collect?","a":"Shells.","wrong":["Rocks.","Coins."]},
       {"q":"What broke the castle?","a":"The waves.","wrong":["The wind.","A dog."]}],
     "clozeType":"category",
     "cloze":[{"text":"We built a big ___.","answer":"sandcastle","wrong":["snowman","treehouse"]},
       {"text":"We swam in the ___.","answer":"sea","wrong":["pool","river"]},
       {"text":"We collected many ___.","answer":"shells","wrong":["stones","leaves"]},
       {"text":"The ___ broke our castle.","answer":"waves","wrong":["wind","rain"]}],
     "reorder":[["We","went","to","the","beach","on","Sunday"],["We","built","a","big","sandcastle"],
       ["We","collected","many","shells"],["The","waves","broke","our","castle"]],
     "dictation":["We went to the beach on Sunday.","We built a big sandcastle.",
       "We collected many shells.","The waves broke our castle."]}},
]

B1 = [
  {"id":"001","title":"001 · A New Hobby","scene":"new-hobby","aria":"Mia and Leo talk about a new hobby",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Mia","R":"Leo","lbub":"Hobby!","rbub":"Guitar!",
   "props":[("🎸",168,116,28,True),("🎵",44,146,22),("🥁",318,140,28)],
   "dialogue":[("Mia","I have started a new hobby."),("Leo","Really? What have you started?"),
     ("Mia","I have started playing the guitar."),("Leo","That's cool! How long have you played?"),
     ("Mia","I have played for three months."),("Leo","Is it difficult to learn?"),
     ("Mia","It was hard at first, but I practice every day."),("Leo","I think music is a great hobby."),
     ("Mia","You should try it too, if you have time."),("Leo","Maybe I will learn the drums!")],
   "content":{
     "quiz3":[{"q":"Mia has started a new hobby.","answer":"Yes"},{"q":"Mia has started playing the guitar.","answer":"Yes"},
       {"q":"Mia has played for three months.","answer":"Yes"},{"q":"Mia practices every day.","answer":"Yes"},
       {"q":"Leo might learn the drums.","answer":"Yes"}],
     "quiz4":[{"q":"Mia has started playing the piano.","answer":"No"},{"q":"Mia has played for three years.","answer":"No"},
       {"q":"Mia never practices.","answer":"No"},{"q":"Leo thinks music is a great hobby.","answer":"Yes"},
       {"q":"Mia plays the guitar.","answer":"Yes"}],
     "vocab":[{"word":"Mia","pic":"👧"},{"word":"Leo","pic":"👦"},{"word":"guitar","pic":"🎸"},
       {"word":"music","pic":"🎵"},{"word":"drums","pic":"🥁"},{"word":"hobby","pic":"🎨"}],
     "wh":[{"q":"What new hobby has Mia started?","a":"Playing the guitar.","wrong":["Playing football.","Painting."]},
       {"q":"How long has Mia played?","a":"For three months.","wrong":["For three years.","For one week."]},
       {"q":"How often does Mia practice?","a":"Every day.","wrong":["Once a month.","Never."]},
       {"q":"What does Leo think about music?","a":"He thinks it is a great hobby.","wrong":["He thinks it is boring.","He thinks it is hard."]},
       {"q":"What might Leo learn?","a":"He might learn the drums.","wrong":["He might learn the piano.","He might learn to cook."]}],
     "clozeType":"context",
     "cloze":[{"text":"I have started playing the ___.","answer":"guitar","wrong":["winter","corner"]},
       {"text":"I have played for three ___.","answer":"months","wrong":["pencils","colors"]},
       {"text":"I ___ every day.","answer":"practice","wrong":["sleep","forget"]},
       {"text":"Music is a great ___.","answer":"hobby","wrong":["weather","dinner"]}],
     "reorder":[["I","have","started","a","new","hobby"],["How","long","have","you","played"],
       ["I","have","played","for","three","months"],["You","should","try","it","too"]],
     "dictation":["I have started a new hobby.","I have started playing the guitar.",
       "I have played for three months.","I practice every day."]}},

  {"id":"002","title":"002 · Planning a Trip","scene":"plan-trip","aria":"Tom and Anna plan a trip",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Tom","R":"Anna","lbub":"Travel!","rbub":"Plan!",
   "props":[("🗺️",168,116,28,True),("🧳",44,146,24),("⛰️",320,118,34)],
   "dialogue":[("Tom","If the weather is nice, we will go to the mountains."),("Anna","That sounds great! What should we bring?"),
     ("Tom","We should bring water, snacks, and a map."),("Anna","How will we get there?"),
     ("Tom","If we leave early, we can take the morning train."),("Anna","What will we do if it rains?"),
     ("Tom","If it rains, we will visit a museum instead."),("Anna","Good idea. We should plan carefully."),
     ("Tom","I think it will be an exciting trip."),("Anna","I can't wait!")],
   "content":{
     "quiz3":[{"q":"They will go to the mountains if the weather is nice.","answer":"Yes"},
       {"q":"They should bring water, snacks, and a map.","answer":"Yes"},
       {"q":"They can take the morning train if they leave early.","answer":"Yes"},
       {"q":"If it rains, they will visit a museum.","answer":"Yes"},{"q":"They should plan carefully.","answer":"Yes"}],
     "quiz4":[{"q":"They will go to the beach.","answer":"No"},{"q":"They should bring nothing.","answer":"No"},
       {"q":"If it rains, they will stay in the mountains.","answer":"No"},
       {"q":"They will take the train if they leave early.","answer":"Yes"},
       {"q":"Tom thinks the trip will be exciting.","answer":"Yes"}],
     "vocab":[{"word":"Tom","pic":"👦"},{"word":"Anna","pic":"👧"},{"word":"mountain","pic":"⛰️"},
       {"word":"map","pic":"🗺️"},{"word":"train","pic":"🚆"},{"word":"museum","pic":"🏛️"}],
     "wh":[{"q":"Where will they go if the weather is nice?","a":"To the mountains.","wrong":["To the beach.","To the city."]},
       {"q":"What should they bring?","a":"Water, snacks, and a map.","wrong":["Only money.","A tent and a boat."]},
       {"q":"How will they get there?","a":"By the morning train.","wrong":["By plane.","By boat."]},
       {"q":"What will they do if it rains?","a":"Visit a museum.","wrong":["Go swimming.","Stay home and sleep."]},
       {"q":"How should they plan?","a":"Carefully.","wrong":["Quickly.","Never."]}],
     "clozeType":"context",
     "cloze":[{"text":"If the weather is nice, we will go to the ___.","answer":"mountains","wrong":["mornings","colors"]},
       {"text":"We should bring water, snacks, and a ___.","answer":"map","wrong":["winter","reason"]},
       {"text":"We can take the morning ___.","answer":"train","wrong":["lunch","story"]},
       {"text":"If it rains, we will visit a ___.","answer":"museum","wrong":["quickly","happy"]}],
     "reorder":[["If","the","weather","is","nice","we","will","go"],["We","should","bring","water","and","snacks"],
       ["If","it","rains","we","will","visit","a","museum"],["We","should","plan","carefully"]],
     "dictation":["If the weather is nice, we will go to the mountains.","We should bring water, snacks, and a map.",
       "If it rains, we will visit a museum.","We should plan carefully."]}},

  {"id":"003","title":"003 · My Favorite Book","scene":"fav-book","aria":"Lily and Sam talk about a favorite book",
   "grad":PURPLE,"decor":G.SUN+G.cloud(70),"L":"Lily","R":"Sam","lbub":"Book!","rbub":"Magic!",
   "props":[("📕",168,116,28,True),("🐉",44,146,26),("🔮",320,144,22)],
   "dialogue":[("Lily","Have you read this book?"),("Sam","No, not yet. What is it about?"),
     ("Lily","It's about a boy who discovers a magic world."),("Sam","That sounds interesting. Is it good?"),
     ("Lily","Yes, I think it's the best book I have ever read."),("Sam","Why do you like it so much?"),
     ("Lily","Because the story is exciting, although the ending is sad."),("Sam","I prefer funny stories, but I will try it."),
     ("Lily","You should read it. I'm sure you will enjoy it."),("Sam","Okay, can I borrow it?")],
   "content":{
     "quiz3":[{"q":"The book is about a boy and a magic world.","answer":"Yes"},
       {"q":"Lily thinks it is the best book she has read.","answer":"Yes"},
       {"q":"Lily likes it because the story is exciting.","answer":"Yes"},{"q":"The ending is sad.","answer":"Yes"},
       {"q":"Sam will try the book.","answer":"Yes"}],
     "quiz4":[{"q":"The book is about a girl and a robot.","answer":"No"},{"q":"Lily thinks it is boring.","answer":"No"},
       {"q":"The ending is happy.","answer":"No"},{"q":"Sam prefers funny stories.","answer":"Yes"},
       {"q":"Sam will borrow the book.","answer":"Yes"}],
     "vocab":[{"word":"Lily","pic":"👧"},{"word":"Sam","pic":"👦"},{"word":"book","pic":"📕"},
       {"word":"story","pic":"📖"},{"word":"magic","pic":"🔮"},{"word":"dragon","pic":"🐉"}],
     "wh":[{"q":"What is the book about?","a":"A boy who discovers a magic world.","wrong":["A girl and her dog.","A famous chef."]},
       {"q":"What does Lily think of it?","a":"It is the best book she has ever read.","wrong":["It is boring.","It is too long."]},
       {"q":"Why does Lily like it?","a":"Because the story is exciting.","wrong":["Because it is short.","Because it has pictures."]},
       {"q":"How is the ending?","a":"Sad.","wrong":["Happy.","Funny."]},
       {"q":"What kind of stories does Sam prefer?","a":"Funny stories.","wrong":["Sad stories.","Scary stories."]}],
     "clozeType":"context",
     "cloze":[{"text":"It's about a boy who discovers a magic ___.","answer":"world","wrong":["lunch","corner"]},
       {"text":"I think it's the best book I have ever ___.","answer":"read","wrong":["slept","eaten"]},
       {"text":"The story is exciting, although the ending is ___.","answer":"sad","wrong":["yellow","loud"]},
       {"text":"I prefer funny ___.","answer":"stories","wrong":["weathers","windows"]}],
     "reorder":[["Have","you","read","this","book"],["It","is","about","a","magic","world"],
       ["It","is","the","best","book","I","have","read"],["I","prefer","funny","stories"]],
     "dictation":["Have you read this book?","It is about a boy who discovers a magic world.",
       "I think it is the best book I have ever read.","I prefer funny stories."]}},

  {"id":"004","title":"004 · Helping the Environment","scene":"environment","aria":"Emma and Ben talk about helping the environment",
   "grad":SKY,"decor":G.SUN+G.cloud(66),"L":"Emma","R":"Ben","lbub":"Save!","rbub":"Trees!",
   "props":[("🌳",168,114,32,True),("🗑️",44,146,24),("🌍",320,120,30)],
   "dialogue":[("Emma","Our town has a pollution problem."),("Ben","I know. The river is very dirty now."),
     ("Emma","We should do something to help."),("Ben","We could pick up trash every weekend."),
     ("Emma","That's a good idea. We could also plant trees."),("Ben","However, we need more people to join us."),
     ("Emma","Let's tell our friends and our class."),("Ben","If everyone helps, we can make a difference."),
     ("Emma","A clean town is better for everyone."),("Ben","Let's start this Saturday!")],
   "content":{
     "quiz3":[{"q":"The town has a pollution problem.","answer":"Yes"},{"q":"The river is dirty.","answer":"Yes"},
       {"q":"They could pick up trash every weekend.","answer":"Yes"},{"q":"They could also plant trees.","answer":"Yes"},
       {"q":"If everyone helps, they can make a difference.","answer":"Yes"}],
     "quiz4":[{"q":"The town has no problems.","answer":"No"},{"q":"The river is clean.","answer":"No"},
       {"q":"They want fewer people to help.","answer":"No"},{"q":"They could plant trees.","answer":"Yes"},
       {"q":"They will start on Saturday.","answer":"Yes"}],
     "vocab":[{"word":"Emma","pic":"👧"},{"word":"Ben","pic":"👦"},{"word":"river","pic":"🏞️"},
       {"word":"trash","pic":"🗑️"},{"word":"tree","pic":"🌳"},{"word":"Earth","pic":"🌍"}],
     "wh":[{"q":"What problem does the town have?","a":"Pollution.","wrong":["Too much rain.","No schools."]},
       {"q":"How is the river now?","a":"Very dirty.","wrong":["Very clean.","Frozen."]},
       {"q":"What could they do every weekend?","a":"Pick up trash.","wrong":["Watch TV.","Go shopping."]},
       {"q":"What else could they do?","a":"Plant trees.","wrong":["Cut trees.","Build roads."]},
       {"q":"When will they start?","a":"This Saturday.","wrong":["Next year.","Never."]}],
     "clozeType":"context",
     "cloze":[{"text":"Our town has a pollution ___.","answer":"problem","wrong":["breakfast","color"]},
       {"text":"We could pick up ___ every weekend.","answer":"trash","wrong":["music","weather"]},
       {"text":"We could also plant ___.","answer":"trees","wrong":["mornings","stories"]},
       {"text":"If everyone helps, we can make a ___.","answer":"difference","wrong":["sandwich","pencil"]}],
     "reorder":[["We","should","do","something","to","help"],["We","could","pick","up","trash"],
       ["We","could","also","plant","trees"],["If","everyone","helps","we","can","make","a","difference"]],
     "dictation":["Our town has a pollution problem.","We should do something to help.",
       "We could plant trees.","If everyone helps, we can make a difference."]}},

  {"id":"005","title":"005 · A Difficult Decision","scene":"decision","aria":"Leo and Mia talk about a difficult decision",
   "grad":("#fef9c3","#fffbeb"),"decor":G.SUN+G.cloud(70),"L":"Leo","R":"Mia","lbub":"Hmm!","rbub":"Choose!",
   "props":[("🤔",168,116,30,True),("🎵",44,146,22),("⚽",320,144,24)],
   "dialogue":[("Leo","I have a difficult decision to make."),("Mia","What's the problem?"),
     ("Leo","I can join the music club or the soccer team, but not both."),("Mia","Which one do you like more?"),
     ("Leo","I love music, but soccer keeps me healthy."),("Mia","I think you should choose the one you enjoy most."),
     ("Leo","Maybe I could try music this year and soccer next year."),("Mia","That sounds like a smart plan."),
     ("Leo","You're right. I will choose the music club first."),("Mia","Good luck! I'm sure you made the right choice.")],
   "content":{
     "quiz3":[{"q":"Leo has a difficult decision.","answer":"Yes"},
       {"q":"He can join the music club or the soccer team.","answer":"Yes"},{"q":"He loves music.","answer":"Yes"},
       {"q":"Mia thinks he should choose what he enjoys most.","answer":"Yes"},
       {"q":"Leo will choose the music club first.","answer":"Yes"}],
     "quiz4":[{"q":"Leo has an easy decision.","answer":"No"},{"q":"He can join both clubs.","answer":"No"},
       {"q":"Leo hates music.","answer":"No"},{"q":"Soccer keeps Leo healthy.","answer":"Yes"},
       {"q":"Leo will try soccer next year.","answer":"Yes"}],
     "vocab":[{"word":"Leo","pic":"👦"},{"word":"Mia","pic":"👧"},{"word":"music","pic":"🎵"},
       {"word":"soccer","pic":"⚽"},{"word":"plan","pic":"📋"},{"word":"choice","pic":"🤔"}],
     "wh":[{"q":"What does Leo have to make?","a":"A difficult decision.","wrong":["A new friend.","A cake."]},
       {"q":"What are his two choices?","a":"The music club or the soccer team.","wrong":["Math or science.","A cat or a dog."]},
       {"q":"Why does he like soccer?","a":"It keeps him healthy.","wrong":["It is easy.","His friends play."]},
       {"q":"What does Mia suggest?","a":"Choose what he enjoys most.","wrong":["Join both.","Quit everything."]},
       {"q":"What will Leo choose first?","a":"The music club.","wrong":["The soccer team.","Nothing."]}],
     "clozeType":"context",
     "cloze":[{"text":"I have a difficult ___ to make.","answer":"decision","wrong":["breakfast","window"]},
       {"text":"I love music, but soccer keeps me ___.","answer":"healthy","wrong":["yellow","loud"]},
       {"text":"You should choose the one you ___ most.","answer":"enjoy","wrong":["sleep","forget"]},
       {"text":"That sounds like a smart ___.","answer":"plan","wrong":["weather","color"]}],
     "reorder":[["I","have","a","difficult","decision","to","make"],["Which","one","do","you","like","more"],
       ["You","should","choose","the","one","you","enjoy"],["I","will","choose","the","music","club","first"]],
     "dictation":["I have a difficult decision to make.","I love music, but soccer keeps me healthy.",
       "You should choose the one you enjoy most.","I will choose the music club first."]}},
]

def ensure_level(m, lid, name, icon, stars, desc):
    for lv in m["levels"]:
        if lv["id"] == lid:
            return lv
    lv = {"id": lid, "name": name, "icon": icon, "stars": stars, "desc": desc, "articles": []}
    m["levels"].append(lv)
    return lv

def write_batch(m, level, prefix, arts):
    have = {x["id"] for x in level["articles"]}
    for a in arts:
        f = prefix + "/" + a["id"]
        G.write(f, "\n".join("%s: %s" % (w, t) for w, t in a["dialogue"]) + "\n")
        G.write(f + ".json", json.dumps(a["content"], ensure_ascii=False, indent=2) + "\n")
        G.write("scenes/" + a["scene"] + ".svg", G.scene_svg(a))
        if a["id"] not in have:
            level["articles"].append({"id": a["id"], "title": a["title"], "file": prefix + "/" + a["id"],
                                      "scene": a["scene"], "levels": [1, 2, 3, 4, 5, 6, 7, 8, 9]})
    level["articles"].sort(key=lambda x: x["id"])

def main():
    m = json.load(open("lessons.json", encoding="utf-8"))
    for name, c in G.CHARS.items():
        m["speakers"].setdefault(name, c["sex"])
    a1 = next(lv for lv in m["levels"] if lv["id"] == "A1")
    write_batch(m, a1, "A1", A1)
    b1 = ensure_level(m, "B1", "B1", "🌲", 4,
                      "Intermediate. Give opinions and reasons, use present perfect and conditionals (if ... will).")
    write_batch(m, b1, "B1", B1)
    G.write("lessons.json", json.dumps(m, ensure_ascii=False, indent=2) + "\n")
    print("wrote", len(A1), "A1 +", len(B1), "B1 articles + scenes")

if __name__ == "__main__":
    main()
