#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""批次產生 Pre-A1 015–024（簡單現在式 / sight words / 具體名詞）。
   關卡 [1,2,3,4,5,7,9]（無 reorder/dictation），cloze 用 recognition。
   從 english_learning/ 執行：  python tools/gen_prea1_more.py
"""
import json
import gen_lessons as G

SKY = G.SKY
BLUE = ("#7dd3fc", "#e0f2fe")

A = [
  {"id":"015","title":"015 · My School Bag","scene":"school-bag","aria":"Tom and Anna look at a school bag",
   "grad":SKY,"decor":G.SUN+G.cloud(64),"L":"Tom","R":"Anna","lbub":"Bag!","rbub":"Blue!",
   "props":[("🎒",168,116,30,True),("✏️",44,146,24),("📖",320,142,24)],
   "dialogue":[("Tom","Look at my school bag."),("Anna","It is blue. I like it."),("Tom","I have a book in my bag."),
     ("Anna","What else is in your bag?"),("Tom","I have a pencil and a ruler."),("Anna","Do you have a pencil case?"),
     ("Tom","Yes, it is red."),("Anna","My bag is green."),("Tom","Your bag is big!"),("Anna","Yes, I put my lunch in it.")],
   "content":{
     "quiz3":[{"q":"Tom has a school bag.","answer":"Yes"},{"q":"Tom's bag is blue.","answer":"Yes"},
       {"q":"Tom has a book.","answer":"Yes"},{"q":"Tom has a pencil and a ruler.","answer":"Yes"},
       {"q":"Anna's bag is green.","answer":"Yes"}],
     "quiz4":[{"q":"Anna's bag is blue.","answer":"No"},{"q":"Tom has a cat in his bag.","answer":"No"},
       {"q":"Tom's pencil case is red.","answer":"Yes"},{"q":"Anna's bag is small.","answer":"No"},
       {"q":"Anna puts her lunch in her bag.","answer":"Yes"}],
     "vocab":[{"word":"Tom","pic":"👦"},{"word":"Anna","pic":"👧"},{"word":"bag","pic":"🎒"},
       {"word":"book","pic":"📖"},{"word":"pencil","pic":"✏️"},{"word":"ruler","pic":"📏"}],
     "wh":[{"q":"What color is Tom's bag?","a":"It is blue.","wrong":["It is red.","It is green."]},
       {"q":"What does Tom have in his bag?","a":"A book.","wrong":["A ball.","A dog."]},
       {"q":"What color is the pencil case?","a":"It is red.","wrong":["It is blue.","It is yellow."]},
       {"q":"What color is Anna's bag?","a":"It is green.","wrong":["It is blue.","It is pink."]},
       {"q":"What does Anna put in her bag?","a":"Her lunch.","wrong":["Her shoes.","Her cat."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"Look at my school ___.","answer":"bag","wrong":["blue","like"]},
       {"text":"I have a ___ in my bag.","answer":"book","wrong":["red","big"]},
       {"text":"I have a pencil and a ___.","answer":"ruler","wrong":["blue","have"]},
       {"text":"My pencil case is ___.","answer":"red","wrong":["bag","book"]}]}},

  {"id":"016","title":"016 · I Like Fruit","scene":"fruit","aria":"Lily and Ben eat fruit",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Lily","R":"Ben","lbub":"Apple!","rbub":"Banana!",
   "props":[("🍎",44,146,26),("🍌",320,144,26),("🍊",168,116,28,True)],
   "dialogue":[("Lily","I am hungry."),("Ben","Here is some fruit."),("Lily","I like apples."),("Ben","I like bananas."),
     ("Lily","Do you like oranges?"),("Ben","Yes, oranges are sweet."),("Lily","This apple is red."),
     ("Ben","This banana is yellow."),("Lily","Fruit is good for us."),("Ben","Let us eat!")],
   "content":{
     "quiz3":[{"q":"Lily is hungry.","answer":"Yes"},{"q":"Lily likes apples.","answer":"Yes"},
       {"q":"Ben likes bananas.","answer":"Yes"},{"q":"Oranges are sweet.","answer":"Yes"},
       {"q":"Fruit is good for us.","answer":"Yes"}],
     "quiz4":[{"q":"Ben is hungry.","answer":"No"},{"q":"Lily likes bananas.","answer":"No"},
       {"q":"The apple is green.","answer":"No"},{"q":"Ben likes oranges.","answer":"Yes"},
       {"q":"The banana is yellow.","answer":"Yes"}],
     "vocab":[{"word":"Lily","pic":"👧"},{"word":"Ben","pic":"👦"},{"word":"apple","pic":"🍎"},
       {"word":"banana","pic":"🍌"},{"word":"orange","pic":"🍊"},{"word":"fruit","pic":"🍇"}],
     "wh":[{"q":"Who is hungry?","a":"Lily is hungry.","wrong":["Ben is hungry.","Mom is hungry."]},
       {"q":"What does Lily like?","a":"She likes apples.","wrong":["She likes cake.","She likes meat."]},
       {"q":"What does Ben like?","a":"He likes bananas.","wrong":["He likes apples.","He likes candy."]},
       {"q":"How do oranges taste?","a":"They are sweet.","wrong":["They are sour.","They are salty."]},
       {"q":"What color is the apple?","a":"It is red.","wrong":["It is blue.","It is black."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"I like ___.","answer":"apples","wrong":["sweet","good"]},
       {"text":"Oranges are ___.","answer":"sweet","wrong":["apple","eat"]},
       {"text":"This apple is ___.","answer":"red","wrong":["fruit","eat"]},
       {"text":"Fruit is good for ___.","answer":"us","wrong":["red","sweet"]}]}},

  {"id":"017","title":"017 · The Big Bus","scene":"bus","aria":"Sam and Mia ride a big bus",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Sam","R":"Mia","lbub":"Bus!","rbub":"Yellow!",
   "props":[("🚌",168,116,30,True),("🏫",320,118,32),("🛞",44,148,22)],
   "dialogue":[("Sam","Look! A big bus."),("Mia","The bus is yellow."),("Sam","I go to school by bus."),
     ("Mia","How many wheels does it have?"),("Sam","It has six wheels."),("Mia","The bus is very long."),
     ("Sam","I sit by the window."),("Mia","I like the bus."),("Sam","The bus is fast."),("Mia","Beep beep! Let us go.")],
   "content":{
     "quiz3":[{"q":"The bus is big.","answer":"Yes"},{"q":"The bus is yellow.","answer":"Yes"},
       {"q":"Sam goes to school by bus.","answer":"Yes"},{"q":"The bus has six wheels.","answer":"Yes"},
       {"q":"The bus is fast.","answer":"Yes"}],
     "quiz4":[{"q":"The bus is small.","answer":"No"},{"q":"The bus is red.","answer":"No"},
       {"q":"Sam walks to school.","answer":"No"},{"q":"Mia likes the bus.","answer":"Yes"},
       {"q":"Sam sits by the window.","answer":"Yes"}],
     "vocab":[{"word":"Sam","pic":"👦"},{"word":"Mia","pic":"👧"},{"word":"bus","pic":"🚌"},
       {"word":"wheel","pic":"🛞"},{"word":"window","pic":"🪟"},{"word":"school","pic":"🏫"}],
     "wh":[{"q":"What color is the bus?","a":"It is yellow.","wrong":["It is red.","It is green."]},
       {"q":"How does Sam go to school?","a":"By bus.","wrong":["By car.","On foot."]},
       {"q":"How many wheels?","a":"Six wheels.","wrong":["Two wheels.","Ten wheels."]},
       {"q":"Where does Sam sit?","a":"By the window.","wrong":["On the floor.","Near the door."]},
       {"q":"How is the bus?","a":"It is fast.","wrong":["It is slow.","It is broken."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"The bus is ___.","answer":"yellow","wrong":["wheel","window"]},
       {"text":"I go to school by ___.","answer":"bus","wrong":["yellow","fast"]},
       {"text":"It has six ___.","answer":"wheels","wrong":["yellow","big"]},
       {"text":"I sit by the ___.","answer":"window","wrong":["bus","fast"]}]}},

  {"id":"018","title":"018 · My New Shoes","scene":"shoes","aria":"Emma shows Leo her new shoes",
   "grad":SKY,"decor":G.SUN+G.cloud(66),"L":"Emma","R":"Leo","lbub":"Shoes!","rbub":"White!",
   "props":[("👟",168,116,28,True),("🧦",44,146,24),("🏃",320,140,26)],
   "dialogue":[("Emma","Look at my new shoes!"),("Leo","Wow, they are white."),("Emma","I can run fast in them."),
     ("Leo","Can you jump too?"),("Emma","Yes, I can jump high."),("Leo","I like your shoes."),
     ("Emma","I wear socks with my shoes."),("Leo","My shoes are old."),("Emma","Let us run together."),
     ("Leo","Okay, ready, set, go!")],
   "content":{
     "quiz3":[{"q":"Emma has new shoes.","answer":"Yes"},{"q":"The shoes are white.","answer":"Yes"},
       {"q":"Emma can run fast.","answer":"Yes"},{"q":"Emma can jump high.","answer":"Yes"},
       {"q":"Emma wears socks.","answer":"Yes"}],
     "quiz4":[{"q":"Leo has new shoes.","answer":"No"},{"q":"The shoes are black.","answer":"No"},
       {"q":"Emma can not run.","answer":"No"},{"q":"Leo's shoes are old.","answer":"Yes"},
       {"q":"They will run together.","answer":"Yes"}],
     "vocab":[{"word":"Emma","pic":"👧"},{"word":"Leo","pic":"👦"},{"word":"shoes","pic":"👟"},
       {"word":"socks","pic":"🧦"},{"word":"run","pic":"🏃"},{"word":"jump","pic":"🦘"}],
     "wh":[{"q":"What color are the shoes?","a":"They are white.","wrong":["They are black.","They are red."]},
       {"q":"What can Emma do in them?","a":"Run fast.","wrong":["Swim fast.","Fly high."]},
       {"q":"Can Emma jump?","a":"Yes, she can jump high.","wrong":["No, she can not.","She can sit."]},
       {"q":"What does Emma wear with shoes?","a":"Socks.","wrong":["A hat.","Gloves."]},
       {"q":"How are Leo's shoes?","a":"They are old.","wrong":["They are new.","They are big."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"Look at my new ___.","answer":"shoes","wrong":["white","run"]},
       {"text":"They are ___.","answer":"white","wrong":["shoes","jump"]},
       {"text":"I can run ___.","answer":"fast","wrong":["shoes","socks"]},
       {"text":"I wear ___ with my shoes.","answer":"socks","wrong":["fast","run"]}]}},

  {"id":"019","title":"019 · Wash Your Hands","scene":"wash-hands","aria":"Anna and Sam wash hands",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Anna","R":"Sam","lbub":"Wash!","rbub":"Clean!",
   "props":[("🧼",44,146,24),("💧",168,118,26,True),("🧻",320,142,24)],
   "dialogue":[("Anna","My hands are dirty."),("Sam","You must wash your hands."),("Anna","I use soap and water."),
     ("Sam","Rub, rub, rub!"),("Anna","Now my hands are clean."),("Sam","Good job!"),
     ("Anna","We wash before we eat."),("Sam","Clean hands are healthy."),("Anna","I dry my hands with a towel."),
     ("Sam","Now we can eat. Yum!")],
   "content":{
     "quiz3":[{"q":"Anna's hands are dirty.","answer":"Yes"},{"q":"Anna uses soap and water.","answer":"Yes"},
       {"q":"Now Anna's hands are clean.","answer":"Yes"},{"q":"We wash before we eat.","answer":"Yes"},
       {"q":"Anna dries her hands with a towel.","answer":"Yes"}],
     "quiz4":[{"q":"Anna's hands are clean at first.","answer":"No"},{"q":"Anna uses milk to wash.","answer":"No"},
       {"q":"We wash after we eat.","answer":"No"},{"q":"Clean hands are healthy.","answer":"Yes"},
       {"q":"Sam says good job.","answer":"Yes"}],
     "vocab":[{"word":"Anna","pic":"👧"},{"word":"Sam","pic":"👦"},{"word":"hands","pic":"🙌"},
       {"word":"soap","pic":"🧼"},{"word":"water","pic":"💧"},{"word":"towel","pic":"🧻"}],
     "wh":[{"q":"How are Anna's hands at first?","a":"They are dirty.","wrong":["They are clean.","They are wet."]},
       {"q":"What does Anna use?","a":"Soap and water.","wrong":["Milk and sugar.","Sand."]},
       {"q":"When do we wash hands?","a":"Before we eat.","wrong":["After we sleep.","Never."]},
       {"q":"What does Anna dry with?","a":"A towel.","wrong":["A shoe.","A book."]},
       {"q":"How are clean hands?","a":"Healthy.","wrong":["Dirty.","Sick."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"My hands are ___.","answer":"dirty","wrong":["soap","wash"]},
       {"text":"I use soap and ___.","answer":"water","wrong":["clean","dirty"]},
       {"text":"Now my hands are ___.","answer":"clean","wrong":["soap","towel"]},
       {"text":"I dry my hands with a ___.","answer":"towel","wrong":["clean","wash"]}]}},

  {"id":"020","title":"020 · The Little Duck","scene":"duck-pond","aria":"Mia and Tom watch a little duck",
   "grad":BLUE,"ground":("#bae6fd","#7dd3fc"),"decor":G.SUN+G.cloud(70),"L":"Mia","R":"Tom","lbub":"Duck!","rbub":"Quack!",
   "props":[("🦆",168,116,30,True),("🪶",44,146,22),("💧",320,148,22)],
   "dialogue":[("Mia","Look at the little duck."),("Tom","It is yellow and small."),("Mia","The duck can swim."),
     ("Tom","It swims in the pond."),("Mia","Quack, quack!"),("Tom","The duck says quack."),
     ("Mia","The duck has two wings."),("Tom","It can flap its wings."),("Mia","I like the little duck."),("Tom","Me too!")],
   "content":{
     "quiz3":[{"q":"There is a little duck.","answer":"Yes"},{"q":"The duck is yellow.","answer":"Yes"},
       {"q":"The duck can swim.","answer":"Yes"},{"q":"The duck swims in the pond.","answer":"Yes"},
       {"q":"The duck has two wings.","answer":"Yes"}],
     "quiz4":[{"q":"The duck is big.","answer":"No"},{"q":"The duck is blue.","answer":"No"},
       {"q":"The duck can not swim.","answer":"No"},{"q":"The duck says quack.","answer":"Yes"},
       {"q":"The duck can flap its wings.","answer":"Yes"}],
     "vocab":[{"word":"Mia","pic":"👧"},{"word":"Tom","pic":"👦"},{"word":"duck","pic":"🦆"},
       {"word":"pond","pic":"💧"},{"word":"swim","pic":"🏊"},{"word":"wing","pic":"🪶"}],
     "wh":[{"q":"What color is the duck?","a":"It is yellow.","wrong":["It is red.","It is green."]},
       {"q":"How big is the duck?","a":"It is small.","wrong":["It is big.","It is tall."]},
       {"q":"What can the duck do?","a":"It can swim.","wrong":["It can drive.","It can read."]},
       {"q":"Where does the duck swim?","a":"In the pond.","wrong":["In a cup.","In the sky."]},
       {"q":"What does the duck say?","a":"Quack.","wrong":["Moo.","Woof."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"Look at the little ___.","answer":"duck","wrong":["yellow","swim"]},
       {"text":"The duck can ___.","answer":"swim","wrong":["duck","pond"]},
       {"text":"It swims in the ___.","answer":"pond","wrong":["swim","yellow"]},
       {"text":"The duck has two ___.","answer":"wings","wrong":["swim","pond"]}]}},

  {"id":"021","title":"021 · My Teddy Bear","scene":"teddy","aria":"Ben shows Lily his teddy bear",
   "grad":("#fce7f3","#fdf2f8"),"decor":G.SUN+G.cloud(70),"L":"Ben","R":"Lily","lbub":"Bear!","rbub":"Cute!",
   "props":[("🧸",168,116,30,True),("🛏️",44,146,26),("⭐",320,58,22)],
   "dialogue":[("Ben","This is my teddy bear."),("Lily","It is so cute!"),("Ben","My bear is brown and soft."),
     ("Lily","What is its name?"),("Ben","Its name is Fluffy."),("Lily","Do you sleep with it?"),
     ("Ben","Yes, every night."),("Lily","I have a teddy bear too."),("Ben","I hug my bear."),
     ("Lily","Teddy bears are the best!")],
   "content":{
     "quiz3":[{"q":"Ben has a teddy bear.","answer":"Yes"},{"q":"The bear is brown and soft.","answer":"Yes"},
       {"q":"The bear's name is Fluffy.","answer":"Yes"},{"q":"Ben sleeps with it every night.","answer":"Yes"},
       {"q":"Lily has a teddy bear too.","answer":"Yes"}],
     "quiz4":[{"q":"Lily has the bear named Fluffy.","answer":"No"},{"q":"The bear is hard.","answer":"No"},
       {"q":"The bear is green.","answer":"No"},{"q":"Ben hugs his bear.","answer":"Yes"},
       {"q":"Ben sleeps with the bear.","answer":"Yes"}],
     "vocab":[{"word":"Ben","pic":"👦"},{"word":"Lily","pic":"👧"},{"word":"bear","pic":"🧸"},
       {"word":"hug","pic":"🤗"},{"word":"sleep","pic":"😴"},{"word":"night","pic":"🌙"}],
     "wh":[{"q":"What does Ben have?","a":"A teddy bear.","wrong":["A dog.","A ball."]},
       {"q":"What color is the bear?","a":"It is brown.","wrong":["It is blue.","It is white."]},
       {"q":"What is the bear's name?","a":"Fluffy.","wrong":["Max.","Coco."]},
       {"q":"When does Ben sleep with it?","a":"Every night.","wrong":["Every morning.","Never."]},
       {"q":"What does Ben do with his bear?","a":"He hugs it.","wrong":["He throws it.","He eats it."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"This is my teddy ___.","answer":"bear","wrong":["soft","cute"]},
       {"text":"My bear is brown and ___.","answer":"soft","wrong":["bear","hug"]},
       {"text":"Its ___ is Fluffy.","answer":"name","wrong":["soft","hug"]},
       {"text":"I ___ my bear.","answer":"hug","wrong":["bear","night"]}]}},

  {"id":"022","title":"022 · Ice Cream Day","scene":"ice-cream","aria":"Sam and Emma eat ice cream on a hot day",
   "grad":("#fde68a","#fffbeb"),"decor":G.SUN+G.cloud(70),"L":"Sam","R":"Emma","lbub":"Hot!","rbub":"Yummy!",
   "props":[("🍦",168,116,30,True),("🧊",44,146,24),("🍓",320,144,22)],
   "dialogue":[("Sam","It is a hot day."),("Emma","Let us get ice cream!"),("Sam","I want chocolate ice cream."),
     ("Emma","I want strawberry."),("Sam","My ice cream is cold."),("Emma","Mine is sweet and yummy."),
     ("Sam","Oh no, it is melting!"),("Emma","Eat it fast!"),("Sam","Yum, I love ice cream."),("Emma","Me too!")],
   "content":{
     "quiz3":[{"q":"It is a hot day.","answer":"Yes"},{"q":"Sam wants chocolate ice cream.","answer":"Yes"},
       {"q":"Emma wants strawberry.","answer":"Yes"},{"q":"The ice cream is cold.","answer":"Yes"},
       {"q":"The ice cream is melting.","answer":"Yes"}],
     "quiz4":[{"q":"It is a cold day.","answer":"No"},{"q":"Sam wants strawberry.","answer":"No"},
       {"q":"Emma wants chocolate.","answer":"No"},{"q":"Sam loves ice cream.","answer":"Yes"},
       {"q":"The ice cream is sweet.","answer":"Yes"}],
     "vocab":[{"word":"Sam","pic":"👦"},{"word":"Emma","pic":"👧"},{"word":"ice cream","pic":"🍦"},
       {"word":"hot","pic":"☀️"},{"word":"cold","pic":"🧊"},{"word":"sweet","pic":"🍬"}],
     "wh":[{"q":"How is the day?","a":"It is hot.","wrong":["It is cold.","It is rainy."]},
       {"q":"What does Sam want?","a":"Chocolate ice cream.","wrong":["Strawberry.","Vanilla."]},
       {"q":"What does Emma want?","a":"Strawberry.","wrong":["Chocolate.","Mango."]},
       {"q":"How is the ice cream?","a":"It is cold.","wrong":["It is hot.","It is warm."]},
       {"q":"What happens to the ice cream?","a":"It melts.","wrong":["It freezes.","It grows."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"It is a hot ___.","answer":"day","wrong":["cold","sweet"]},
       {"text":"I want chocolate ice ___.","answer":"cream","wrong":["hot","cold"]},
       {"text":"My ice cream is ___.","answer":"cold","wrong":["cream","day"]},
       {"text":"Oh no, it is ___!","answer":"melting","wrong":["cold","sweet"]}]}},

  {"id":"023","title":"023 · The Kite","scene":"kite","aria":"Leo and Mia fly a kite",
   "grad":("#bfdbfe","#eff6ff"),"decor":G.cloud(70)+G.cloud(250,"cloud2"),"L":"Leo","R":"Mia","lbub":"Kite!","rbub":"High!",
   "props":[("🪁",150,56,30,True),("🌬️",44,140,24),("🧵",320,146,22)],
   "dialogue":[("Leo","Look at my kite!"),("Mia","It is red and big."),("Leo","The wind is strong today."),
     ("Mia","Your kite flies high!"),("Leo","It goes up in the sky."),("Mia","Can I hold it?"),
     ("Leo","Yes, hold the string."),("Mia","This is so much fun!"),("Leo","Let us fly it together."),("Mia","I love kites!")],
   "content":{
     "quiz3":[{"q":"Leo has a kite.","answer":"Yes"},{"q":"The kite is red and big.","answer":"Yes"},
       {"q":"The wind is strong.","answer":"Yes"},{"q":"The kite flies high.","answer":"Yes"},
       {"q":"Mia holds the string.","answer":"Yes"}],
     "quiz4":[{"q":"Mia has the kite.","answer":"No"},{"q":"The kite is small.","answer":"No"},
       {"q":"There is no wind.","answer":"No"},{"q":"The kite flies high.","answer":"Yes"},
       {"q":"They fly it together.","answer":"Yes"}],
     "vocab":[{"word":"Leo","pic":"👦"},{"word":"Mia","pic":"👧"},{"word":"kite","pic":"🪁"},
       {"word":"wind","pic":"🌬️"},{"word":"sky","pic":"☁️"},{"word":"string","pic":"🧵"}],
     "wh":[{"q":"What does Leo have?","a":"A kite.","wrong":["A ball.","A bike."]},
       {"q":"What color is the kite?","a":"It is red.","wrong":["It is blue.","It is green."]},
       {"q":"How is the wind?","a":"It is strong.","wrong":["It is gone.","It is cold."]},
       {"q":"Where does the kite fly?","a":"In the sky.","wrong":["In the sea.","Under the bed."]},
       {"q":"What does Mia hold?","a":"The string.","wrong":["The bus.","The dog."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"Look at my ___!","answer":"kite","wrong":["red","big"]},
       {"text":"The ___ is strong.","answer":"wind","wrong":["kite","high"]},
       {"text":"It goes up in the ___.","answer":"sky","wrong":["kite","wind"]},
       {"text":"Hold the ___.","answer":"string","wrong":["sky","wind"]}]}},

  {"id":"024","title":"024 · Feed the Fish","scene":"fish-tank","aria":"Anna and Ben feed the fish",
   "grad":BLUE,"ground":("#bae6fd","#7dd3fc"),"decor":G.SUN+G.cloud(70),"L":"Anna","R":"Ben","lbub":"Fish!","rbub":"Orange!",
   "props":[("🐠",168,116,30,True),("💧",44,148,22),("🍚",320,144,22)],
   "dialogue":[("Anna","Look at my fish."),("Ben","They are orange."),("Anna","I have three fish."),
     ("Ben","Where do they live?"),("Anna","They live in a tank."),("Ben","The fish can swim."),
     ("Anna","It is time to feed them."),("Ben","What do fish eat?"),("Anna","They eat fish food."),("Ben","The fish are happy!")],
   "content":{
     "quiz3":[{"q":"Anna has fish.","answer":"Yes"},{"q":"The fish are orange.","answer":"Yes"},
       {"q":"Anna has three fish.","answer":"Yes"},{"q":"The fish live in a tank.","answer":"Yes"},
       {"q":"The fish eat fish food.","answer":"Yes"}],
     "quiz4":[{"q":"Ben has the fish.","answer":"No"},{"q":"The fish are blue.","answer":"No"},
       {"q":"Anna has ten fish.","answer":"No"},{"q":"The fish can swim.","answer":"Yes"},
       {"q":"Anna feeds the fish.","answer":"Yes"}],
     "vocab":[{"word":"Anna","pic":"👧"},{"word":"Ben","pic":"👦"},{"word":"fish","pic":"🐠"},
       {"word":"water","pic":"💧"},{"word":"food","pic":"🍚"},{"word":"swim","pic":"🏊"}],
     "wh":[{"q":"What does Anna have?","a":"Fish.","wrong":["A cat.","A bird."]},
       {"q":"What color are the fish?","a":"They are orange.","wrong":["They are red.","They are black."]},
       {"q":"How many fish?","a":"Three fish.","wrong":["One fish.","Ten fish."]},
       {"q":"Where do the fish live?","a":"In a tank.","wrong":["In a box.","In the sky."]},
       {"q":"What do the fish eat?","a":"Fish food.","wrong":["Cake.","Grass."]}],
     "clozeType":"recognition",
     "cloze":[{"text":"Look at my ___.","answer":"fish","wrong":["orange","swim"]},
       {"text":"They live in a ___.","answer":"tank","wrong":["fish","swim"]},
       {"text":"The fish can ___.","answer":"swim","wrong":["tank","fish"]},
       {"text":"They eat fish ___.","answer":"food","wrong":["swim","tank"]}]}},
]

def main():
    m = json.load(open("lessons.json", encoding="utf-8"))
    for name, c in G.CHARS.items():
        m["speakers"].setdefault(name, c["sex"])
    pre = next(lv for lv in m["levels"] if lv["id"] == "Pre-A1")
    have = {x["id"] for x in pre["articles"]}
    for a in A:
        f = "Pre-A1/" + a["id"]
        G.write(f, "\n".join("%s: %s" % (w, t) for w, t in a["dialogue"]) + "\n")
        G.write(f + ".json", json.dumps(a["content"], ensure_ascii=False, indent=2) + "\n")
        G.write("scenes/" + a["scene"] + ".svg", G.scene_svg(a))
        if a["id"] not in have:
            pre["articles"].append({"id": a["id"], "title": a["title"], "file": "Pre-A1/" + a["id"],
                                    "scene": a["scene"], "levels": [1, 2, 3, 4, 5, 7, 9]})
    pre["articles"].sort(key=lambda x: x["id"])
    G.write("lessons.json", json.dumps(m, ensure_ascii=False, indent=2) + "\n")
    print("wrote", len(A), "Pre-A1 articles + scenes")

if __name__ == "__main__":
    main()
