#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""批次產生 A2 課程 003–012：對話、<file>.json（含 reorder/dictation）、scenes、manifest。
   沿用 gen_lessons.py 的角色/場景產生器（同一套換色小孩）。
   從 english_learning/ 執行：  python tools/gen_a2.py
"""
import json, os
import gen_lessons as G

SKY = G.SKY
def SUN(): return G.SUN
def cloud(cx): return G.cloud(cx)

# 10 篇 A2 文章（未來式 / because / should / 比較級 / 過去+未來）
A = [
  {"id":"003","title":"003 · My Future Job","scene":"future-job","aria":"Leo and Mia talk about future jobs",
   "grad":SKY,"decor":G.SUN+G.cloud(64),"L":"Leo","R":"Mia","lbub":"Pilot!","rbub":"Doctor!",
   "props":[("✈️",168,108,28,True),("🩺",44,146,24),("🏥",320,120,30)],
   "dialogue":[("Leo","What do you want to be?"),("Mia","I want to be a doctor."),("Leo","Why do you want to be a doctor?"),
     ("Mia","Because I want to help sick people."),("Leo","That is a great job!"),("Mia","What about you, Leo?"),
     ("Leo","I want to be a pilot."),("Mia","Wow! Why a pilot?"),("Leo","Because I love airplanes and the sky."),
     ("Mia","We should study hard for our dreams.")],
   "content":{
     "quiz3":[{"q":"Mia wants to be a doctor.","answer":"Yes"},{"q":"Mia wants to help sick people.","answer":"Yes"},
       {"q":"Leo wants to be a pilot.","answer":"Yes"},{"q":"Leo loves airplanes.","answer":"Yes"},
       {"q":"They should study hard.","answer":"Yes"}],
     "quiz4":[{"q":"Leo wants to be a doctor.","answer":"No"},{"q":"Mia wants to be a pilot.","answer":"No"},
       {"q":"Mia wants to help sick people.","answer":"Yes"},{"q":"Leo is afraid of the sky.","answer":"No"},
       {"q":"They will study hard for their dreams.","answer":"Yes"}],
     "vocab":[{"word":"Leo","pic":"👦"},{"word":"Mia","pic":"👧"},{"word":"doctor","pic":"🩺"},
       {"word":"pilot","pic":"🧑‍✈️"},{"word":"airplane","pic":"✈️"},{"word":"hospital","pic":"🏥"}],
     "wh":[{"q":"What does Mia want to be?","a":"She wants to be a doctor.","wrong":["She wants to be a teacher.","She wants to be a singer."]},
       {"q":"Why does Mia want to be a doctor?","a":"Because she wants to help sick people.","wrong":["Because she likes money.","Because it is easy."]},
       {"q":"What does Leo want to be?","a":"He wants to be a pilot.","wrong":["He wants to be a doctor.","He wants to be a chef."]},
       {"q":"Why does Leo want to be a pilot?","a":"Because he loves airplanes.","wrong":["Because he hates flying.","Because his mom said so."]},
       {"q":"What should they do for their dreams?","a":"They should study hard.","wrong":["They should sleep all day.","They should give up."]}],
     "clozeType":"context",
     "cloze":[{"text":"I want to be a ___.","answer":"doctor","wrong":["holiday","weather"]},
       {"text":"I want to help ___ people.","answer":"sick","wrong":["sunny","fast"]},
       {"text":"I want to be a pilot because I love ___.","answer":"airplanes","wrong":["homework","rain"]},
       {"text":"We should ___ hard for our dreams.","answer":"study","wrong":["sleep","cry"]}],
     "reorder":[["I","want","to","be","a","doctor"],["Why","do","you","want","to","be","a","pilot"],
       ["Because","I","love","airplanes","and","the","sky"],["We","should","study","hard","for","our","dreams"]],
     "dictation":["I want to be a doctor.","I want to help sick people.",
       "I want to be a pilot because I love airplanes.","We should study hard for our dreams."]}},

  {"id":"004","title":"004 · The School Trip","scene":"school-trip","aria":"Tom and Anna plan a school trip",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Tom","R":"Anna","lbub":"Trip!","rbub":"Museum!",
   "props":[("🚌",168,116,30,True),("🎒",44,148,22),("🏛️",320,120,32)],
   "dialogue":[("Tom","Where will we go on the school trip?"),("Anna","We will go to the science museum."),
     ("Tom","That sounds fun! How will we get there?"),("Anna","We will go by bus."),
     ("Tom","What will we see at the museum?"),("Anna","We will see robots and dinosaurs."),
     ("Tom","I want to see the dinosaurs because they are huge."),("Anna","Don't forget to bring your lunch."),
     ("Tom","I will bring a sandwich and some water."),("Anna","It will be a great day!")],
   "content":{
     "quiz3":[{"q":"They will go on a school trip.","answer":"Yes"},{"q":"They will go to the science museum.","answer":"Yes"},
       {"q":"They will go by bus.","answer":"Yes"},{"q":"They will see robots and dinosaurs.","answer":"Yes"},
       {"q":"Tom will bring a sandwich.","answer":"Yes"}],
     "quiz4":[{"q":"They will go to the zoo.","answer":"No"},{"q":"They will go by train.","answer":"No"},
       {"q":"Tom wants to see the dinosaurs.","answer":"Yes"},{"q":"Anna says to forget your lunch.","answer":"No"},
       {"q":"It will be a great day.","answer":"Yes"}],
     "vocab":[{"word":"Tom","pic":"👦"},{"word":"Anna","pic":"👧"},{"word":"museum","pic":"🏛️"},
       {"word":"bus","pic":"🚌"},{"word":"robot","pic":"🤖"},{"word":"dinosaur","pic":"🦖"},{"word":"sandwich","pic":"🥪"}],
     "wh":[{"q":"Where will they go?","a":"They will go to the science museum.","wrong":["They will go to the beach.","They will go to the farm."]},
       {"q":"How will they get there?","a":"They will go by bus.","wrong":["They will go by plane.","They will go by boat."]},
       {"q":"What will they see?","a":"They will see robots and dinosaurs.","wrong":["They will see lions and bears.","They will see ships."]},
       {"q":"Why does Tom want to see the dinosaurs?","a":"Because they are huge.","wrong":["Because they are small.","Because they are scary."]},
       {"q":"What will Tom bring?","a":"He will bring a sandwich and water.","wrong":["He will bring a cake.","He will bring a tent."]}],
     "clozeType":"context",
     "cloze":[{"text":"We will go to the science ___.","answer":"museum","wrong":["dinner","morning"]},
       {"text":"We will go by ___.","answer":"bus","wrong":["lunch","rain"]},
       {"text":"We will see robots and ___.","answer":"dinosaurs","wrong":["weekends","colors"]},
       {"text":"I want to see them because they are ___.","answer":"huge","wrong":["quiet","late"]}],
     "reorder":[["We","will","go","to","the","museum"],["How","will","we","get","there"],
       ["We","will","go","by","bus"],["I","want","to","see","the","dinosaurs"]],
     "dictation":["We will go to the science museum.","We will go by bus.",
       "We will see robots and dinosaurs.","I will bring a sandwich and some water."]}},

  {"id":"005","title":"005 · Healthy Habits","scene":"healthy","aria":"Emma and Ben talk about healthy habits",
   "grad":SKY,"decor":G.SUN+G.cloud(66),"L":"Emma","R":"Ben","lbub":"Healthy!","rbub":"Veggies!",
   "props":[("🥦",44,148,24),("🍎",80,150,20),("🏃",168,116,26,True),("💧",322,142,22)],
   "dialogue":[("Emma","You look great, Ben!"),("Ben","Thanks! I eat healthy food now."),("Emma","What do you eat?"),
     ("Ben","I eat vegetables and fruit every day."),("Emma","Do you drink soda?"),
     ("Ben","No, I drink water because soda is bad for me."),("Emma","That is a good habit."),
     ("Ben","I also run every morning."),("Emma","Why do you run?"),("Ben","Because exercise makes me strong.")],
   "content":{
     "quiz3":[{"q":"Ben eats healthy food.","answer":"Yes"},{"q":"Ben eats vegetables and fruit.","answer":"Yes"},
       {"q":"Ben drinks water.","answer":"Yes"},{"q":"Ben runs every morning.","answer":"Yes"},
       {"q":"Exercise makes Ben strong.","answer":"Yes"}],
     "quiz4":[{"q":"Ben eats junk food.","answer":"No"},{"q":"Ben drinks soda every day.","answer":"No"},
       {"q":"Ben thinks soda is good for him.","answer":"No"},{"q":"Ben runs in the morning.","answer":"Yes"},
       {"q":"Ben wants to be strong.","answer":"Yes"}],
     "vocab":[{"word":"Emma","pic":"👧"},{"word":"Ben","pic":"👦"},{"word":"vegetables","pic":"🥦"},
       {"word":"fruit","pic":"🍎"},{"word":"water","pic":"💧"},{"word":"soda","pic":"🥤"},{"word":"run","pic":"🏃"}],
     "wh":[{"q":"What does Ben eat?","a":"He eats vegetables and fruit.","wrong":["He eats candy and chips.","He eats cake."]},
       {"q":"What does Ben drink?","a":"He drinks water.","wrong":["He drinks soda.","He drinks juice."]},
       {"q":"Why doesn't Ben drink soda?","a":"Because it is bad for him.","wrong":["Because it is too sweet to buy.","Because he has none."]},
       {"q":"When does Ben run?","a":"He runs every morning.","wrong":["He runs every night.","He never runs."]},
       {"q":"Why does Ben run?","a":"Because exercise makes him strong.","wrong":["Because he likes to be tired.","Because his mom runs."]}],
     "clozeType":"pos",
     "cloze":[{"text":"I eat ___ every day.","answer":"vegetables","wrong":["quickly","green"]},
       {"text":"Soda is ___ for me.","answer":"bad","wrong":["badly","run"]},
       {"text":"I ___ every morning.","answer":"run","wrong":["runner","fast"]},
       {"text":"Exercise makes me ___.","answer":"strong","wrong":["strongly","strength"]}],
     "reorder":[["I","eat","vegetables","and","fruit","every","day"],["I","drink","water","because","soda","is","bad"],
       ["I","run","every","morning"],["Exercise","makes","me","strong"]],
     "dictation":["I eat vegetables and fruit every day.","I drink water because soda is bad for me.",
       "I run every morning.","Exercise makes me strong."]}},

  {"id":"006","title":"006 · A Rainy Picnic","scene":"rainy-picnic","aria":"Lily and Sam plan an indoor picnic",
   "grad":("#94a3b8","#cbd5e1"),"decor":G.grey_cloud(110)+G.grey_cloud(240,"cloud2")+G.RAIN,
   "L":"Lily","R":"Sam","lbub":"Picnic!","rbub":"Rain!",
   "props":[("🧺",168,118,28,True),("🥪",44,146,22),("🍰",322,144,22)],
   "dialogue":[("Lily","We were going to have a picnic today."),("Sam","But it started to rain."),
     ("Lily","I made sandwiches and a cake."),("Sam","Don't be sad. We can eat inside."),
     ("Lily","That is a good idea."),("Sam","We can have an indoor picnic on the floor."),
     ("Lily","Let's put a blanket in the living room."),("Sam","I will bring the juice."),
     ("Lily","This is fun, even without the sun!"),("Sam","Next time the weather will be better.")],
   "content":{
     "quiz3":[{"q":"They were going to have a picnic.","answer":"Yes"},{"q":"It started to rain.","answer":"Yes"},
       {"q":"Lily made sandwiches and a cake.","answer":"Yes"},{"q":"They will eat inside.","answer":"Yes"},
       {"q":"Sam will bring the juice.","answer":"Yes"}],
     "quiz4":[{"q":"They had the picnic in the park.","answer":"No"},{"q":"It was sunny all day.","answer":"No"},
       {"q":"Sam tells Lily to be sad.","answer":"No"},{"q":"They have an indoor picnic.","answer":"Yes"},
       {"q":"Lily made some food.","answer":"Yes"}],
     "vocab":[{"word":"Lily","pic":"👧"},{"word":"Sam","pic":"👦"},{"word":"picnic","pic":"🧺"},
       {"word":"rain","pic":"🌧️"},{"word":"sandwich","pic":"🥪"},{"word":"cake","pic":"🍰"},{"word":"juice","pic":"🧃"}],
     "wh":[{"q":"What were they going to do?","a":"They were going to have a picnic.","wrong":["They were going to swim.","They were going to sleep."]},
       {"q":"Why couldn't they have the picnic outside?","a":"Because it started to rain.","wrong":["Because it was too hot.","Because they were sick."]},
       {"q":"What did Lily make?","a":"She made sandwiches and a cake.","wrong":["She made soup.","She made pizza."]},
       {"q":"Where will they have the picnic?","a":"They will have it inside.","wrong":["They will have it at school.","They will have it on the bus."]},
       {"q":"What will Sam bring?","a":"He will bring the juice.","wrong":["He will bring the rain.","He will bring a dog."]}],
     "clozeType":"context",
     "cloze":[{"text":"We were going to have a ___.","answer":"picnic","wrong":["winter","corner"]},
       {"text":"But it started to ___.","answer":"rain","wrong":["sleep","read"]},
       {"text":"We can eat ___.","answer":"inside","wrong":["loudly","yellow"]},
       {"text":"Next time the ___ will be better.","answer":"weather","wrong":["pencil","music"]}],
     "reorder":[["We","were","going","to","have","a","picnic"],["But","it","started","to","rain"],
       ["We","can","eat","inside"],["I","will","bring","the","juice"]],
     "dictation":["We were going to have a picnic today.","But it started to rain.",
       "We can have an indoor picnic.","Next time the weather will be better."]}},

  {"id":"007","title":"007 · Saving Money","scene":"saving-money","aria":"Sam and Mia talk about saving money",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Sam","R":"Mia","lbub":"Save!","rbub":"Bike!",
   "props":[("🐷",168,116,28,True),("💰",44,146,24),("🚲",318,140,28)],
   "dialogue":[("Sam","I am saving my money."),("Mia","Why are you saving money?"),
     ("Sam","Because I want to buy a new bike."),("Mia","How much does the bike cost?"),
     ("Sam","It costs fifty dollars."),("Mia","How much do you have now?"),("Sam","I have thirty dollars."),
     ("Mia","So you need twenty more dollars."),("Sam","Yes. I will save for two more weeks."),
     ("Mia","Good luck! I am sure you can do it.")],
   "content":{
     "quiz3":[{"q":"Sam is saving money.","answer":"Yes"},{"q":"Sam wants to buy a bike.","answer":"Yes"},
       {"q":"The bike costs fifty dollars.","answer":"Yes"},{"q":"Sam has thirty dollars.","answer":"Yes"},
       {"q":"Sam needs twenty more dollars.","answer":"Yes"}],
     "quiz4":[{"q":"Mia is saving money.","answer":"No"},{"q":"Sam wants to buy a car.","answer":"No"},
       {"q":"The bike costs thirty dollars.","answer":"No"},{"q":"Sam will save for two more weeks.","answer":"Yes"},
       {"q":"Mia thinks Sam can do it.","answer":"Yes"}],
     "vocab":[{"word":"Sam","pic":"👦"},{"word":"Mia","pic":"👧"},{"word":"money","pic":"💰"},
       {"word":"bike","pic":"🚲"},{"word":"dollar","pic":"💵"},{"word":"bank","pic":"🐷"}],
     "wh":[{"q":"Why is Sam saving money?","a":"Because he wants to buy a bike.","wrong":["Because he likes coins.","Because his bank is full."]},
       {"q":"How much does the bike cost?","a":"It costs fifty dollars.","wrong":["It costs five dollars.","It costs ten dollars."]},
       {"q":"How much does Sam have?","a":"He has thirty dollars.","wrong":["He has fifty dollars.","He has nothing."]},
       {"q":"How much more does he need?","a":"He needs twenty more dollars.","wrong":["He needs fifty more.","He needs no more."]},
       {"q":"How long will Sam save?","a":"He will save for two more weeks.","wrong":["He will save for a year.","He will stop today."]}],
     "clozeType":"context",
     "cloze":[{"text":"I want to buy a new ___.","answer":"bike","wrong":["lunch","story"]},
       {"text":"The bike ___ fifty dollars.","answer":"costs","wrong":["sleeps","sings"]},
       {"text":"I have thirty ___.","answer":"dollars","wrong":["windows","songs"]},
       {"text":"I will ___ for two more weeks.","answer":"save","wrong":["fly","draw"]}],
     "reorder":[["I","am","saving","my","money"],["I","want","to","buy","a","new","bike"],
       ["The","bike","costs","fifty","dollars"],["I","will","save","for","two","weeks"]],
     "dictation":["I am saving my money.","I want to buy a new bike.",
       "The bike costs fifty dollars.","I will save for two more weeks."]}},

  {"id":"008","title":"008 · Learning to Swim","scene":"learn-swim","aria":"Ben and Lily talk about learning to swim",
   "grad":("#7dd3fc","#e0f2fe"),"ground":("#bae6fd","#7dd3fc"),"decor":G.SUN+G.cloud(70),
   "L":"Ben","R":"Lily","lbub":"Swim!","rbub":"Pool!",
   "props":[("🏊",168,116,28,True),("🥽",44,146,22),("🌊",320,146,24)],
   "dialogue":[("Ben","I can swim now!"),("Lily","Really? That is great!"),("Ben","Last year I could not swim at all."),
     ("Lily","How did you learn?"),("Ben","My dad taught me every weekend."),("Lily","Where do you practice?"),
     ("Ben","I practice at the swimming pool."),("Lily","Is it difficult?"),
     ("Ben","It was hard at first, but now it is easy."),("Lily","I want to learn how to swim, too.")],
   "content":{
     "quiz3":[{"q":"Ben can swim now.","answer":"Yes"},{"q":"Last year Ben could not swim.","answer":"Yes"},
       {"q":"Ben's dad taught him.","answer":"Yes"},{"q":"Ben practices at the pool.","answer":"Yes"},
       {"q":"Lily wants to learn to swim.","answer":"Yes"}],
     "quiz4":[{"q":"Ben could always swim.","answer":"No"},{"q":"Ben's mom taught him.","answer":"No"},
       {"q":"Ben practices at the beach.","answer":"No"},{"q":"Now swimming is easy for Ben.","answer":"Yes"},
       {"q":"Swimming was easy at first.","answer":"No"}],
     "vocab":[{"word":"Ben","pic":"👦"},{"word":"Lily","pic":"👧"},{"word":"swim","pic":"🏊"},
       {"word":"water","pic":"🌊"},{"word":"goggles","pic":"🥽"},{"word":"dad","pic":"👨"}],
     "wh":[{"q":"What can Ben do now?","a":"He can swim.","wrong":["He can fly.","He can drive."]},
       {"q":"Who taught Ben?","a":"His dad taught him.","wrong":["His teacher taught him.","His sister taught him."]},
       {"q":"Where does Ben practice?","a":"He practices at the swimming pool.","wrong":["He practices at home.","He practices in the sea."]},
       {"q":"When did his dad teach him?","a":"Every weekend.","wrong":["Every night.","Once a year."]},
       {"q":"How was swimming at first?","a":"It was hard.","wrong":["It was easy.","It was boring."]}],
     "clozeType":"context",
     "cloze":[{"text":"I can ___ now.","answer":"swim","wrong":["green","table"]},
       {"text":"My dad ___ me every weekend.","answer":"taught","wrong":["ate","slept"]},
       {"text":"I practice at the swimming ___.","answer":"pool","wrong":["lunch","story"]},
       {"text":"It was hard at first, but now it is ___.","answer":"easy","wrong":["winter","pencil"]}],
     "reorder":[["I","can","swim","now"],["Last","year","I","could","not","swim"],
       ["My","dad","taught","me","every","weekend"],["I","practice","at","the","pool"]],
     "dictation":["I can swim now.","Last year I could not swim.",
       "My dad taught me every weekend.","It was hard at first, but now it is easy."]}},

  {"id":"009","title":"009 · The Science Project","scene":"science-project","aria":"Leo and Emma talk about their science projects",
   "grad":("#ede9fe","#f5f3ff"),"decor":G.SUN+G.cloud(70),"L":"Leo","R":"Emma","lbub":"Plants!","rbub":"Volcano!",
   "props":[("🌋",168,114,30,True),("🔬",44,146,24),("🧪",320,144,24)],
   "dialogue":[("Leo","What is your science project about?"),("Emma","My project is about volcanoes."),
     ("Leo","That sounds cool! What will you make?"),("Emma","I will make a model volcano."),
     ("Leo","How will it work?"),("Emma","It will erupt with baking soda and vinegar."),
     ("Leo","My project is about plants."),("Emma","What are you studying?"),
     ("Leo","I am studying which plant grows faster."),("Emma","Our projects will be the best in the class!")],
   "content":{
     "quiz3":[{"q":"Emma's project is about volcanoes.","answer":"Yes"},{"q":"Emma will make a model volcano.","answer":"Yes"},
       {"q":"The volcano will erupt with baking soda and vinegar.","answer":"Yes"},{"q":"Leo's project is about plants.","answer":"Yes"},
       {"q":"Leo is studying which plant grows faster.","answer":"Yes"}],
     "quiz4":[{"q":"Leo's project is about volcanoes.","answer":"No"},{"q":"Emma will make a model car.","answer":"No"},
       {"q":"Emma's volcano uses water only.","answer":"No"},{"q":"Leo studies plants.","answer":"Yes"},
       {"q":"They think their projects will be the best.","answer":"Yes"}],
     "vocab":[{"word":"Leo","pic":"👦"},{"word":"Emma","pic":"👧"},{"word":"volcano","pic":"🌋"},
       {"word":"plant","pic":"🌱"},{"word":"microscope","pic":"🔬"},{"word":"test tube","pic":"🧪"}],
     "wh":[{"q":"What is Emma's project about?","a":"It is about volcanoes.","wrong":["It is about animals.","It is about cars."]},
       {"q":"What will Emma make?","a":"She will make a model volcano.","wrong":["She will make a cake.","She will make a robot."]},
       {"q":"How will the volcano erupt?","a":"With baking soda and vinegar.","wrong":["With water and sand.","With fire."]},
       {"q":"What is Leo's project about?","a":"It is about plants.","wrong":["It is about stars.","It is about rocks."]},
       {"q":"What is Leo studying?","a":"Which plant grows faster.","wrong":["Which plant is taller.","Which animal is faster."]}],
     "clozeType":"pos",
     "cloze":[{"text":"My project is about ___.","answer":"volcanoes","wrong":["quickly","tall"]},
       {"text":"I will ___ a model volcano.","answer":"make","wrong":["maker","ready"]},
       {"text":"Which plant grows ___?","answer":"faster","wrong":["speed","quick"]},
       {"text":"Our projects will be the ___.","answer":"best","wrong":["well","win"]}],
     "reorder":[["My","project","is","about","volcanoes"],["I","will","make","a","model","volcano"],
       ["My","project","is","about","plants"],["Our","projects","will","be","the","best"]],
     "dictation":["My project is about volcanoes.","I will make a model volcano.",
       "I am studying which plant grows faster.","Our projects will be the best."]}},

  {"id":"010","title":"010 · A Visit to Grandma","scene":"visit-grandma","aria":"Anna and Tom talk about visiting grandma",
   "grad":("#fed7aa","#fff7ed"),"decor":G.SUN+G.cloud(70),"L":"Anna","R":"Tom","lbub":"Grandma!","rbub":"Cookies!",
   "props":[("👵",168,118,30),("🍪",44,148,22),("🏡",318,120,30)],
   "dialogue":[("Anna","Last weekend I visited my grandma."),("Tom","That is nice! What did you do?"),
     ("Anna","We baked cookies together."),("Tom","Yum! Were they good?"),("Anna","Yes, they were delicious."),
     ("Tom","What else did you do?"),("Anna","We watched old photos and she told me stories."),
     ("Tom","Will you visit her again?"),("Anna","Yes, I will visit her next month."),("Tom","Say hello to her for me!")],
   "content":{
     "quiz3":[{"q":"Anna visited her grandma last weekend.","answer":"Yes"},{"q":"They baked cookies.","answer":"Yes"},
       {"q":"The cookies were delicious.","answer":"Yes"},{"q":"Grandma told Anna stories.","answer":"Yes"},
       {"q":"Anna will visit again next month.","answer":"Yes"}],
     "quiz4":[{"q":"Tom visited his grandma.","answer":"No"},{"q":"They baked bread.","answer":"No"},
       {"q":"The cookies were bad.","answer":"No"},{"q":"They looked at old photos.","answer":"Yes"},
       {"q":"Anna will visit her next month.","answer":"Yes"}],
     "vocab":[{"word":"Anna","pic":"👧"},{"word":"Tom","pic":"👦"},{"word":"grandma","pic":"👵"},
       {"word":"cookies","pic":"🍪"},{"word":"photo","pic":"🖼️"},{"word":"story","pic":"📖"}],
     "wh":[{"q":"Who did Anna visit?","a":"She visited her grandma.","wrong":["She visited her teacher.","She visited Tom."]},
       {"q":"What did they bake?","a":"They baked cookies.","wrong":["They baked a cake.","They baked bread."]},
       {"q":"How were the cookies?","a":"They were delicious.","wrong":["They were burnt.","They were cold."]},
       {"q":"What did grandma do?","a":"She told stories.","wrong":["She sang songs.","She slept."]},
       {"q":"When will Anna visit again?","a":"She will visit next month.","wrong":["She will visit next year.","She will not visit."]}],
     "clozeType":"context",
     "cloze":[{"text":"Last weekend I visited my ___.","answer":"grandma","wrong":["summer","corner"]},
       {"text":"We baked ___ together.","answer":"cookies","wrong":["weekends","colors"]},
       {"text":"They were ___.","answer":"delicious","wrong":["yesterday","slowly"]},
       {"text":"I will visit her next ___.","answer":"month","wrong":["apple","music"]}],
     "reorder":[["Last","weekend","I","visited","my","grandma"],["We","baked","cookies","together"],
       ["She","told","me","stories"],["I","will","visit","her","next","month"]],
     "dictation":["Last weekend I visited my grandma.","We baked cookies together.",
       "They were delicious.","I will visit her next month."]}},

  {"id":"011","title":"011 · Recycling at Home","scene":"recycling","aria":"Mia and Leo talk about recycling",
   "grad":SKY,"decor":G.SUN+G.cloud(66),"L":"Mia","R":"Leo","lbub":"Recycle!","rbub":"Earth!",
   "props":[("♻️",168,116,30,True),("🍶",44,148,22),("🌍",320,120,30)],
   "dialogue":[("Mia","What are you doing with those bottles?"),("Leo","I am putting them in the recycling bin."),
     ("Mia","Why do you recycle?"),("Leo","Because it is good for the Earth."),("Mia","What can we recycle?"),
     ("Leo","We can recycle paper, glass, and plastic."),("Mia","I throw everything in the trash."),
     ("Leo","You should recycle, too."),("Mia","Okay, I will start today."),
     ("Leo","Together we can keep our planet clean.")],
   "content":{
     "quiz3":[{"q":"Leo is recycling bottles.","answer":"Yes"},{"q":"Leo recycles because it is good for the Earth.","answer":"Yes"},
       {"q":"They can recycle paper, glass, and plastic.","answer":"Yes"},{"q":"Mia will start recycling today.","answer":"Yes"},
       {"q":"Recycling keeps the planet clean.","answer":"Yes"}],
     "quiz4":[{"q":"Mia is recycling the bottles.","answer":"No"},{"q":"Leo thinks recycling is bad for the Earth.","answer":"No"},
       {"q":"They can only recycle paper.","answer":"No"},{"q":"Mia will start recycling today.","answer":"Yes"},
       {"q":"Leo wants a clean planet.","answer":"Yes"}],
     "vocab":[{"word":"Mia","pic":"👧"},{"word":"Leo","pic":"👦"},{"word":"bottle","pic":"🍶"},
       {"word":"paper","pic":"📄"},{"word":"plastic","pic":"♻️"},{"word":"Earth","pic":"🌍"}],
     "wh":[{"q":"What is Leo doing with the bottles?","a":"He is recycling them.","wrong":["He is eating them.","He is hiding them."]},
       {"q":"Why does Leo recycle?","a":"Because it is good for the Earth.","wrong":["Because it is fun.","Because his mom pays him."]},
       {"q":"What can they recycle?","a":"Paper, glass, and plastic.","wrong":["Food and water.","Cars and trains."]},
       {"q":"What does Mia usually do?","a":"She throws everything in the trash.","wrong":["She recycles everything.","She burns it."]},
       {"q":"What will Mia do?","a":"She will start recycling today.","wrong":["She will stop recycling.","She will move away."]}],
     "clozeType":"pos",
     "cloze":[{"text":"I am ___ the bottles.","answer":"recycling","wrong":["recycle","green"]},
       {"text":"Recycling is good for the ___.","answer":"Earth","wrong":["happily","clean"]},
       {"text":"You ___ recycle, too.","answer":"should","wrong":["quickly","good"]},
       {"text":"We can keep our planet ___.","answer":"clean","wrong":["cleanly","cleaning"]}],
     "reorder":[["I","am","putting","them","in","the","bin"],["Why","do","you","recycle"],
       ["Because","it","is","good","for","the","Earth"],["You","should","recycle","too"]],
     "dictation":["I am putting them in the recycling bin.","I recycle because it is good for the Earth.",
       "We can recycle paper, glass, and plastic.","Together we can keep our planet clean."]}},

  {"id":"012","title":"012 · The Football Match","scene":"football-match","aria":"Sam and Ben get ready for a football match",
   "grad":SKY,"decor":G.SUN+G.cloud(70),"L":"Sam","R":"Ben","lbub":"Goal!","rbub":"Win!",
   "props":[("⚽",168,116,28,True),("🥅",44,140,28),("🏆",322,142,24)],
   "dialogue":[("Sam","Are you ready for the football match?"),("Ben","Yes! I think we will win today."),
     ("Sam","Why do you think we will win?"),("Ben","Because we practiced very hard."),
     ("Sam","Who is the best player on our team?"),("Ben","You are! You run the fastest."),
     ("Sam","Thanks! You score the most goals."),("Ben","If we play together, we will be strong."),
     ("Sam","Let's do our best!"),("Ben","Go team, go!")],
   "content":{
     "quiz3":[{"q":"They are ready for a football match.","answer":"Yes"},{"q":"Ben thinks they will win.","answer":"Yes"},
       {"q":"They practiced very hard.","answer":"Yes"},{"q":"Sam runs the fastest.","answer":"Yes"},
       {"q":"Ben scores the most goals.","answer":"Yes"}],
     "quiz4":[{"q":"They are ready for a swimming race.","answer":"No"},{"q":"Ben thinks they will lose.","answer":"No"},
       {"q":"They did not practice.","answer":"No"},{"q":"Sam is a fast runner.","answer":"Yes"},
       {"q":"They want to do their best.","answer":"Yes"}],
     "vocab":[{"word":"Sam","pic":"👦"},{"word":"Ben","pic":"👦"},{"word":"football","pic":"⚽"},
       {"word":"goal","pic":"🥅"},{"word":"trophy","pic":"🏆"},{"word":"team","pic":"👥"}],
     "wh":[{"q":"What are they ready for?","a":"A football match.","wrong":["A music class.","A spelling test."]},
       {"q":"Why does Ben think they will win?","a":"Because they practiced hard.","wrong":["Because they are lucky.","Because the other team is sick."]},
       {"q":"Who runs the fastest?","a":"Sam runs the fastest.","wrong":["Ben runs the fastest.","The coach runs the fastest."]},
       {"q":"Who scores the most goals?","a":"Ben scores the most goals.","wrong":["Sam scores the most.","Nobody scores."]},
       {"q":"What will make them strong?","a":"Playing together.","wrong":["Playing alone.","Not practicing."]}],
     "clozeType":"context",
     "cloze":[{"text":"I think we will ___ today.","answer":"win","wrong":["sleep","read"]},
       {"text":"Because we ___ very hard.","answer":"practiced","wrong":["smiled","slept"]},
       {"text":"You run the ___.","answer":"fastest","wrong":["dinner","window"]},
       {"text":"You score the most ___.","answer":"goals","wrong":["mornings","colors"]}],
     "reorder":[["I","think","we","will","win","today"],["Because","we","practiced","very","hard"],
       ["You","run","the","fastest"],["If","we","play","together","we","will","be","strong"]],
     "dictation":["I think we will win today.","Because we practiced very hard.",
       "You run the fastest.","If we play together, we will be strong."]}},
]

def main():
    for a in A:
        file = "A2/" + a["id"]
        G.write(file, "\n".join("%s: %s" % (w, t) for w, t in a["dialogue"]) + "\n")
        G.write(file + ".json", json.dumps(a["content"], ensure_ascii=False, indent=2) + "\n")
        G.write("scenes/" + a["scene"] + ".svg", G.scene_svg(a))
    m = json.load(open("lessons.json", encoding="utf-8"))
    for name, c in G.CHARS.items():
        m["speakers"].setdefault(name, c["sex"])
    a2 = next(lv for lv in m["levels"] if lv["id"] == "A2")
    have = {x["id"] for x in a2["articles"]}
    for a in A:
        if a["id"] in have:
            continue
        a2["articles"].append({"id": a["id"], "title": a["title"], "file": "A2/" + a["id"],
                               "scene": a["scene"], "levels": [1, 2, 3, 4, 5, 6, 7, 8, 9]})
    a2["articles"].sort(key=lambda x: x["id"])
    G.write("lessons.json", json.dumps(m, ensure_ascii=False, indent=2) + "\n")
    print("wrote", len(A), "A2 articles + scenes")

if __name__ == "__main__":
    main()
